/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSceneEditorRouteImport } from './routes/api/scene-editor'
import { Route as ApiWebEntryRouteImport } from './routes/api/web-entry'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMarketplaceCatalogRouteImport } from './routes/api/marketplace/catalog'
import { Route as ApiMarketplaceInstallRouteImport } from './routes/api/marketplace/install'
import { Route as ApiMarketplaceInstallPlanRouteImport } from './routes/api/marketplace/install-plan'
import { Route as ApiTelemetryScenePerformanceRouteImport } from './routes/api/telemetry/scene-performance'
import { Route as ApiWorkspacesWorkspaceIdRouteImport } from './routes/api/workspaces/$workspaceId'
import { Route as ApiWorkspacesBootstrapRouteImport } from './routes/api/workspaces/bootstrap'
import { Route as ApiWorkspacesClaimRouteImport } from './routes/api/workspaces/claim'
import { Route as AuthDesktopCompleteRouteImport } from './routes/auth/desktop/complete'
import { Route as ApiAuthDesktopAuthorizeRouteImport } from './routes/api/auth/desktop/authorize'
import { Route as ApiAuthDesktopExchangeRouteImport } from './routes/api/auth/desktop/exchange'
import { Route as ApiAuthDesktopLogoutRouteImport } from './routes/api/auth/desktop/logout'
import { Route as ApiAuthDesktopRefreshRouteImport } from './routes/api/auth/desktop/refresh'
import { Route as ApiAuthDesktopRevokeRouteImport } from './routes/api/auth/desktop/revoke'
import { Route as ApiWorkspacesWorkspaceIdReopenRouteImport } from './routes/api/workspaces/$workspaceId/reopen'
import { Route as ApiV1WorkspacesWorkspaceIdAgentsRouteImport } from './routes/api/v1/workspaces/$workspaceId/agents'
import { Route as ApiV1WorkspacesWorkspaceIdArtifactsRouteImport } from './routes/api/v1/workspaces/$workspaceId/artifacts'
import { Route as ApiV1WorkspacesWorkspaceIdChannelsRouteImport } from './routes/api/v1/workspaces/$workspaceId/channels'
import { Route as ApiV1WorkspacesWorkspaceIdContentRefsRouteImport } from './routes/api/v1/workspaces/$workspaceId/content-refs'
import { Route as ApiV1WorkspacesWorkspaceIdReadStateRouteImport } from './routes/api/v1/workspaces/$workspaceId/read-state'
import { Route as ApiV1WorkspacesWorkspaceIdRoomsRouteImport } from './routes/api/v1/workspaces/$workspaceId/rooms'
import { Route as ApiV1WorkspacesWorkspaceIdSearchRouteImport } from './routes/api/v1/workspaces/$workspaceId/search'
import { Route as ApiV1WorkspacesWorkspaceIdTasksRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks'
import { Route as ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/agents/$agentId'
import { Route as ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
import { Route as ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/channels/$channelId'
import { Route as ApiV1WorkspacesWorkspaceIdContentRefsContentIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/content-refs/$contentId'
import { Route as ApiV1WorkspacesWorkspaceIdMessagesMessageIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/messages/$messageId'
import { Route as ApiV1WorkspacesWorkspaceIdRoomsRoomIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/rooms/$roomId'
import { Route as ApiV1WorkspacesWorkspaceIdRoomsReorderRouteImport } from './routes/api/v1/workspaces/$workspaceId/rooms/reorder'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId'
import { Route as ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRouteImport } from './routes/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
import { Route as ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRouteImport } from './routes/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
import { Route as ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRouteImport } from './routes/api/v1/workspaces/$workspaceId/agents/$agentId/room'
import { Route as ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRouteImport } from './routes/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
import { Route as ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRouteImport } from './routes/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
import { Route as ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
import { Route as ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRouteImport } from './routes/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
import { Route as ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRouteImport } from './routes/api/v1/workspaces/$workspaceId/tasks/$taskId/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSceneEditorRoute = ApiSceneEditorRouteImport.update({
  id: '/api/scene-editor',
  path: '/api/scene-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebEntryRoute = ApiWebEntryRouteImport.update({
  id: '/api/web-entry',
  path: '/api/web-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceCatalogRoute = ApiMarketplaceCatalogRouteImport.update({
  id: '/api/marketplace/catalog',
  path: '/api/marketplace/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceInstallRoute = ApiMarketplaceInstallRouteImport.update({
  id: '/api/marketplace/install',
  path: '/api/marketplace/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceInstallPlanRoute =
  ApiMarketplaceInstallPlanRouteImport.update({
    id: '/api/marketplace/install-plan',
    path: '/api/marketplace/install-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryScenePerformanceRoute =
  ApiTelemetryScenePerformanceRouteImport.update({
    id: '/api/telemetry/scene-performance',
    path: '/api/telemetry/scene-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkspacesWorkspaceIdRoute =
  ApiWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ApiWorkspacesRoute,
  } as any)
const ApiWorkspacesBootstrapRoute = ApiWorkspacesBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const ApiWorkspacesClaimRoute = ApiWorkspacesClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const AuthDesktopCompleteRoute = AuthDesktopCompleteRouteImport.update({
  id: '/auth/desktop/complete',
  path: '/auth/desktop/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopAuthorizeRoute = ApiAuthDesktopAuthorizeRouteImport.update({
  id: '/api/auth/desktop/authorize',
  path: '/api/auth/desktop/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopExchangeRoute = ApiAuthDesktopExchangeRouteImport.update({
  id: '/api/auth/desktop/exchange',
  path: '/api/auth/desktop/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopLogoutRoute = ApiAuthDesktopLogoutRouteImport.update({
  id: '/api/auth/desktop/logout',
  path: '/api/auth/desktop/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopRefreshRoute = ApiAuthDesktopRefreshRouteImport.update({
  id: '/api/auth/desktop/refresh',
  path: '/api/auth/desktop/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopRevokeRoute = ApiAuthDesktopRevokeRouteImport.update({
  id: '/api/auth/desktop/revoke',
  path: '/api/auth/desktop/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesWorkspaceIdReopenRoute =
  ApiWorkspacesWorkspaceIdReopenRouteImport.update({
    id: '/reopen',
    path: '/reopen',
    getParentRoute: () => ApiWorkspacesWorkspaceIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAgentsRoute =
  ApiV1WorkspacesWorkspaceIdAgentsRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/agents',
    path: '/api/v1/workspaces/$workspaceId/agents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdArtifactsRoute =
  ApiV1WorkspacesWorkspaceIdArtifactsRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/artifacts',
    path: '/api/v1/workspaces/$workspaceId/artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdChannelsRoute =
  ApiV1WorkspacesWorkspaceIdChannelsRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/channels',
    path: '/api/v1/workspaces/$workspaceId/channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdContentRefsRoute =
  ApiV1WorkspacesWorkspaceIdContentRefsRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/content-refs',
    path: '/api/v1/workspaces/$workspaceId/content-refs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdReadStateRoute =
  ApiV1WorkspacesWorkspaceIdReadStateRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/read-state',
    path: '/api/v1/workspaces/$workspaceId/read-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdRoomsRoute =
  ApiV1WorkspacesWorkspaceIdRoomsRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/rooms',
    path: '/api/v1/workspaces/$workspaceId/rooms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdSearchRoute =
  ApiV1WorkspacesWorkspaceIdSearchRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/search',
    path: '/api/v1/workspaces/$workspaceId/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksRoute =
  ApiV1WorkspacesWorkspaceIdTasksRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/tasks',
    path: '/api/v1/workspaces/$workspaceId/tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute =
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdAgentsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute =
  ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRouteImport.update({
    id: '/$artifactId',
    path: '/$artifactId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdArtifactsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute =
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdChannelsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute =
  ApiV1WorkspacesWorkspaceIdContentRefsContentIdRouteImport.update({
    id: '/$contentId',
    path: '/$contentId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdContentRefsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute =
  ApiV1WorkspacesWorkspaceIdMessagesMessageIdRouteImport.update({
    id: '/api/v1/workspaces/$workspaceId/messages/$messageId',
    path: '/api/v1/workspaces/$workspaceId/messages/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute =
  ApiV1WorkspacesWorkspaceIdRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdRoomsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdRoomsReorderRoute =
  ApiV1WorkspacesWorkspaceIdRoomsReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdRoomsRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute =
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRouteImport.update({
    id: '/presentation',
    path: '/presentation',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute =
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute =
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRouteImport.update({
    id: '/room',
    path: '/room',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute =
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute =
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute =
  ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdReadStateRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute =
  ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRouteImport.update(
    {
      id: '/threads/$threadRootMessageId',
      path: '/threads/$threadRootMessageId',
      getParentRoute: () => ApiV1WorkspacesWorkspaceIdReadStateRoute,
    } as any,
  )
const ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRouteImport.update({
    id: '/assign',
    path: '/assign',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRouteImport.update({
    id: '/conversation',
    path: '/conversation',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRouteImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRouteImport.update({
    id: '/room',
    path: '/room',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/scene-editor': typeof ApiSceneEditorRoute
  '/api/web-entry': typeof ApiWebEntryRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/marketplace/catalog': typeof ApiMarketplaceCatalogRoute
  '/api/marketplace/install': typeof ApiMarketplaceInstallRoute
  '/api/marketplace/install-plan': typeof ApiMarketplaceInstallPlanRoute
  '/api/telemetry/scene-performance': typeof ApiTelemetryScenePerformanceRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/bootstrap': typeof ApiWorkspacesBootstrapRoute
  '/api/workspaces/claim': typeof ApiWorkspacesClaimRoute
  '/auth/desktop/complete': typeof AuthDesktopCompleteRoute
  '/api/auth/desktop/authorize': typeof ApiAuthDesktopAuthorizeRoute
  '/api/auth/desktop/exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop/logout': typeof ApiAuthDesktopLogoutRoute
  '/api/auth/desktop/refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop/revoke': typeof ApiAuthDesktopRevokeRoute
  '/api/workspaces/$workspaceId/reopen': typeof ApiWorkspacesWorkspaceIdReopenRoute
  '/api/v1/workspaces/$workspaceId/agents': typeof ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts': typeof ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/channels': typeof ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs': typeof ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/read-state': typeof ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren
  '/api/v1/workspaces/$workspaceId/rooms': typeof ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/search': typeof ApiV1WorkspacesWorkspaceIdSearchRoute
  '/api/v1/workspaces/$workspaceId/tasks': typeof ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts/$artifactId': typeof ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs/$contentId': typeof ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute
  '/api/v1/workspaces/$workspaceId/messages/$messageId': typeof ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/$roomId': typeof ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/reorder': typeof ApiV1WorkspacesWorkspaceIdRoomsReorderRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/profile': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/room': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/messages': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/participants': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute
  '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute
  '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId': typeof ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/review': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/room': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/start': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/scene-editor': typeof ApiSceneEditorRoute
  '/api/web-entry': typeof ApiWebEntryRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/marketplace/catalog': typeof ApiMarketplaceCatalogRoute
  '/api/marketplace/install': typeof ApiMarketplaceInstallRoute
  '/api/marketplace/install-plan': typeof ApiMarketplaceInstallPlanRoute
  '/api/telemetry/scene-performance': typeof ApiTelemetryScenePerformanceRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/bootstrap': typeof ApiWorkspacesBootstrapRoute
  '/api/workspaces/claim': typeof ApiWorkspacesClaimRoute
  '/auth/desktop/complete': typeof AuthDesktopCompleteRoute
  '/api/auth/desktop/authorize': typeof ApiAuthDesktopAuthorizeRoute
  '/api/auth/desktop/exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop/logout': typeof ApiAuthDesktopLogoutRoute
  '/api/auth/desktop/refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop/revoke': typeof ApiAuthDesktopRevokeRoute
  '/api/workspaces/$workspaceId/reopen': typeof ApiWorkspacesWorkspaceIdReopenRoute
  '/api/v1/workspaces/$workspaceId/agents': typeof ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts': typeof ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/channels': typeof ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs': typeof ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/read-state': typeof ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren
  '/api/v1/workspaces/$workspaceId/rooms': typeof ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/search': typeof ApiV1WorkspacesWorkspaceIdSearchRoute
  '/api/v1/workspaces/$workspaceId/tasks': typeof ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts/$artifactId': typeof ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs/$contentId': typeof ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute
  '/api/v1/workspaces/$workspaceId/messages/$messageId': typeof ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/$roomId': typeof ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/reorder': typeof ApiV1WorkspacesWorkspaceIdRoomsReorderRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/profile': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/room': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/messages': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/participants': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute
  '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute
  '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId': typeof ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/review': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/room': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/start': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/scene-editor': typeof ApiSceneEditorRoute
  '/api/web-entry': typeof ApiWebEntryRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/marketplace/catalog': typeof ApiMarketplaceCatalogRoute
  '/api/marketplace/install': typeof ApiMarketplaceInstallRoute
  '/api/marketplace/install-plan': typeof ApiMarketplaceInstallPlanRoute
  '/api/telemetry/scene-performance': typeof ApiTelemetryScenePerformanceRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/bootstrap': typeof ApiWorkspacesBootstrapRoute
  '/api/workspaces/claim': typeof ApiWorkspacesClaimRoute
  '/auth/desktop/complete': typeof AuthDesktopCompleteRoute
  '/api/auth/desktop/authorize': typeof ApiAuthDesktopAuthorizeRoute
  '/api/auth/desktop/exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop/logout': typeof ApiAuthDesktopLogoutRoute
  '/api/auth/desktop/refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop/revoke': typeof ApiAuthDesktopRevokeRoute
  '/api/workspaces/$workspaceId/reopen': typeof ApiWorkspacesWorkspaceIdReopenRoute
  '/api/v1/workspaces/$workspaceId/agents': typeof ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts': typeof ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/channels': typeof ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs': typeof ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/read-state': typeof ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren
  '/api/v1/workspaces/$workspaceId/rooms': typeof ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/search': typeof ApiV1WorkspacesWorkspaceIdSearchRoute
  '/api/v1/workspaces/$workspaceId/tasks': typeof ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/artifacts/$artifactId': typeof ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/content-refs/$contentId': typeof ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute
  '/api/v1/workspaces/$workspaceId/messages/$messageId': typeof ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/$roomId': typeof ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute
  '/api/v1/workspaces/$workspaceId/rooms/reorder': typeof ApiV1WorkspacesWorkspaceIdRoomsReorderRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren
  '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/profile': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute
  '/api/v1/workspaces/$workspaceId/agents/$agentId/room': typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/messages': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute
  '/api/v1/workspaces/$workspaceId/channels/$channelId/participants': typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute
  '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId': typeof ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute
  '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId': typeof ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/review': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/room': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute
  '/api/v1/workspaces/$workspaceId/tasks/$taskId/start': typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/scene-editor'
    | '/api/web-entry'
    | '/api/workspaces'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/api/marketplace/catalog'
    | '/api/marketplace/install'
    | '/api/marketplace/install-plan'
    | '/api/telemetry/scene-performance'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/bootstrap'
    | '/api/workspaces/claim'
    | '/auth/desktop/complete'
    | '/api/auth/desktop/authorize'
    | '/api/auth/desktop/exchange'
    | '/api/auth/desktop/logout'
    | '/api/auth/desktop/refresh'
    | '/api/auth/desktop/revoke'
    | '/api/workspaces/$workspaceId/reopen'
    | '/api/v1/workspaces/$workspaceId/agents'
    | '/api/v1/workspaces/$workspaceId/artifacts'
    | '/api/v1/workspaces/$workspaceId/channels'
    | '/api/v1/workspaces/$workspaceId/content-refs'
    | '/api/v1/workspaces/$workspaceId/read-state'
    | '/api/v1/workspaces/$workspaceId/rooms'
    | '/api/v1/workspaces/$workspaceId/search'
    | '/api/v1/workspaces/$workspaceId/tasks'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId'
    | '/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/content-refs/$contentId'
    | '/api/v1/workspaces/$workspaceId/messages/$messageId'
    | '/api/v1/workspaces/$workspaceId/rooms/$roomId'
    | '/api/v1/workspaces/$workspaceId/rooms/reorder'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/room'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
    | '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/scene-editor'
    | '/api/web-entry'
    | '/api/workspaces'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/api/marketplace/catalog'
    | '/api/marketplace/install'
    | '/api/marketplace/install-plan'
    | '/api/telemetry/scene-performance'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/bootstrap'
    | '/api/workspaces/claim'
    | '/auth/desktop/complete'
    | '/api/auth/desktop/authorize'
    | '/api/auth/desktop/exchange'
    | '/api/auth/desktop/logout'
    | '/api/auth/desktop/refresh'
    | '/api/auth/desktop/revoke'
    | '/api/workspaces/$workspaceId/reopen'
    | '/api/v1/workspaces/$workspaceId/agents'
    | '/api/v1/workspaces/$workspaceId/artifacts'
    | '/api/v1/workspaces/$workspaceId/channels'
    | '/api/v1/workspaces/$workspaceId/content-refs'
    | '/api/v1/workspaces/$workspaceId/read-state'
    | '/api/v1/workspaces/$workspaceId/rooms'
    | '/api/v1/workspaces/$workspaceId/search'
    | '/api/v1/workspaces/$workspaceId/tasks'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId'
    | '/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/content-refs/$contentId'
    | '/api/v1/workspaces/$workspaceId/messages/$messageId'
    | '/api/v1/workspaces/$workspaceId/rooms/$roomId'
    | '/api/v1/workspaces/$workspaceId/rooms/reorder'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/room'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
    | '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/start'
  id:
    | '__root__'
    | '/'
    | '/api/scene-editor'
    | '/api/web-entry'
    | '/api/workspaces'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/api/marketplace/catalog'
    | '/api/marketplace/install'
    | '/api/marketplace/install-plan'
    | '/api/telemetry/scene-performance'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/bootstrap'
    | '/api/workspaces/claim'
    | '/auth/desktop/complete'
    | '/api/auth/desktop/authorize'
    | '/api/auth/desktop/exchange'
    | '/api/auth/desktop/logout'
    | '/api/auth/desktop/refresh'
    | '/api/auth/desktop/revoke'
    | '/api/workspaces/$workspaceId/reopen'
    | '/api/v1/workspaces/$workspaceId/agents'
    | '/api/v1/workspaces/$workspaceId/artifacts'
    | '/api/v1/workspaces/$workspaceId/channels'
    | '/api/v1/workspaces/$workspaceId/content-refs'
    | '/api/v1/workspaces/$workspaceId/read-state'
    | '/api/v1/workspaces/$workspaceId/rooms'
    | '/api/v1/workspaces/$workspaceId/search'
    | '/api/v1/workspaces/$workspaceId/tasks'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId'
    | '/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/content-refs/$contentId'
    | '/api/v1/workspaces/$workspaceId/messages/$messageId'
    | '/api/v1/workspaces/$workspaceId/rooms/$roomId'
    | '/api/v1/workspaces/$workspaceId/rooms/reorder'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
    | '/api/v1/workspaces/$workspaceId/agents/$agentId/room'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
    | '/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
    | '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
    | '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
    | '/api/v1/workspaces/$workspaceId/tasks/$taskId/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSceneEditorRoute: typeof ApiSceneEditorRoute
  ApiWebEntryRoute: typeof ApiWebEntryRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMarketplaceCatalogRoute: typeof ApiMarketplaceCatalogRoute
  ApiMarketplaceInstallRoute: typeof ApiMarketplaceInstallRoute
  ApiMarketplaceInstallPlanRoute: typeof ApiMarketplaceInstallPlanRoute
  ApiTelemetryScenePerformanceRoute: typeof ApiTelemetryScenePerformanceRoute
  AuthDesktopCompleteRoute: typeof AuthDesktopCompleteRoute
  ApiAuthDesktopAuthorizeRoute: typeof ApiAuthDesktopAuthorizeRoute
  ApiAuthDesktopExchangeRoute: typeof ApiAuthDesktopExchangeRoute
  ApiAuthDesktopLogoutRoute: typeof ApiAuthDesktopLogoutRoute
  ApiAuthDesktopRefreshRoute: typeof ApiAuthDesktopRefreshRoute
  ApiAuthDesktopRevokeRoute: typeof ApiAuthDesktopRevokeRoute
  ApiV1WorkspacesWorkspaceIdAgentsRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdArtifactsRoute: typeof ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdChannelsRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdContentRefsRoute: typeof ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdReadStateRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren
  ApiV1WorkspacesWorkspaceIdRoomsRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdSearchRoute: typeof ApiV1WorkspacesWorkspaceIdSearchRoute
  ApiV1WorkspacesWorkspaceIdTasksRoute: typeof ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren
  ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute: typeof ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scene-editor': {
      id: '/api/scene-editor'
      path: '/api/scene-editor'
      fullPath: '/api/scene-editor'
      preLoaderRoute: typeof ApiSceneEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-entry': {
      id: '/api/web-entry'
      path: '/api/web-entry'
      fullPath: '/api/web-entry'
      preLoaderRoute: typeof ApiWebEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/catalog': {
      id: '/api/marketplace/catalog'
      path: '/api/marketplace/catalog'
      fullPath: '/api/marketplace/catalog'
      preLoaderRoute: typeof ApiMarketplaceCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/install': {
      id: '/api/marketplace/install'
      path: '/api/marketplace/install'
      fullPath: '/api/marketplace/install'
      preLoaderRoute: typeof ApiMarketplaceInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/install-plan': {
      id: '/api/marketplace/install-plan'
      path: '/api/marketplace/install-plan'
      fullPath: '/api/marketplace/install-plan'
      preLoaderRoute: typeof ApiMarketplaceInstallPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/scene-performance': {
      id: '/api/telemetry/scene-performance'
      path: '/api/telemetry/scene-performance'
      fullPath: '/api/telemetry/scene-performance'
      preLoaderRoute: typeof ApiTelemetryScenePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId': {
      id: '/api/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/api/workspaces/$workspaceId'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/workspaces/bootstrap': {
      id: '/api/workspaces/bootstrap'
      path: '/bootstrap'
      fullPath: '/api/workspaces/bootstrap'
      preLoaderRoute: typeof ApiWorkspacesBootstrapRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/workspaces/claim': {
      id: '/api/workspaces/claim'
      path: '/claim'
      fullPath: '/api/workspaces/claim'
      preLoaderRoute: typeof ApiWorkspacesClaimRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/auth/desktop/complete': {
      id: '/auth/desktop/complete'
      path: '/auth/desktop/complete'
      fullPath: '/auth/desktop/complete'
      preLoaderRoute: typeof AuthDesktopCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop/authorize': {
      id: '/api/auth/desktop/authorize'
      path: '/api/auth/desktop/authorize'
      fullPath: '/api/auth/desktop/authorize'
      preLoaderRoute: typeof ApiAuthDesktopAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop/exchange': {
      id: '/api/auth/desktop/exchange'
      path: '/api/auth/desktop/exchange'
      fullPath: '/api/auth/desktop/exchange'
      preLoaderRoute: typeof ApiAuthDesktopExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop/logout': {
      id: '/api/auth/desktop/logout'
      path: '/api/auth/desktop/logout'
      fullPath: '/api/auth/desktop/logout'
      preLoaderRoute: typeof ApiAuthDesktopLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop/refresh': {
      id: '/api/auth/desktop/refresh'
      path: '/api/auth/desktop/refresh'
      fullPath: '/api/auth/desktop/refresh'
      preLoaderRoute: typeof ApiAuthDesktopRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop/revoke': {
      id: '/api/auth/desktop/revoke'
      path: '/api/auth/desktop/revoke'
      fullPath: '/api/auth/desktop/revoke'
      preLoaderRoute: typeof ApiAuthDesktopRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId/reopen': {
      id: '/api/workspaces/$workspaceId/reopen'
      path: '/reopen'
      fullPath: '/api/workspaces/$workspaceId/reopen'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdReopenRouteImport
      parentRoute: typeof ApiWorkspacesWorkspaceIdRoute
    }
    '/api/v1/workspaces/$workspaceId/agents': {
      id: '/api/v1/workspaces/$workspaceId/agents'
      path: '/api/v1/workspaces/$workspaceId/agents'
      fullPath: '/api/v1/workspaces/$workspaceId/agents'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/artifacts': {
      id: '/api/v1/workspaces/$workspaceId/artifacts'
      path: '/api/v1/workspaces/$workspaceId/artifacts'
      fullPath: '/api/v1/workspaces/$workspaceId/artifacts'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/channels': {
      id: '/api/v1/workspaces/$workspaceId/channels'
      path: '/api/v1/workspaces/$workspaceId/channels'
      fullPath: '/api/v1/workspaces/$workspaceId/channels'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/content-refs': {
      id: '/api/v1/workspaces/$workspaceId/content-refs'
      path: '/api/v1/workspaces/$workspaceId/content-refs'
      fullPath: '/api/v1/workspaces/$workspaceId/content-refs'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdContentRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/read-state': {
      id: '/api/v1/workspaces/$workspaceId/read-state'
      path: '/api/v1/workspaces/$workspaceId/read-state'
      fullPath: '/api/v1/workspaces/$workspaceId/read-state'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/rooms': {
      id: '/api/v1/workspaces/$workspaceId/rooms'
      path: '/api/v1/workspaces/$workspaceId/rooms'
      fullPath: '/api/v1/workspaces/$workspaceId/rooms'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/search': {
      id: '/api/v1/workspaces/$workspaceId/search'
      path: '/api/v1/workspaces/$workspaceId/search'
      fullPath: '/api/v1/workspaces/$workspaceId/search'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/tasks': {
      id: '/api/v1/workspaces/$workspaceId/tasks'
      path: '/api/v1/workspaces/$workspaceId/tasks'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/agents/$agentId': {
      id: '/api/v1/workspaces/$workspaceId/agents/$agentId'
      path: '/$agentId'
      fullPath: '/api/v1/workspaces/$workspaceId/agents/$agentId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsRoute
    }
    '/api/v1/workspaces/$workspaceId/artifacts/$artifactId': {
      id: '/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/api/v1/workspaces/$workspaceId/artifacts/$artifactId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdArtifactsRoute
    }
    '/api/v1/workspaces/$workspaceId/channels/$channelId': {
      id: '/api/v1/workspaces/$workspaceId/channels/$channelId'
      path: '/$channelId'
      fullPath: '/api/v1/workspaces/$workspaceId/channels/$channelId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsRoute
    }
    '/api/v1/workspaces/$workspaceId/content-refs/$contentId': {
      id: '/api/v1/workspaces/$workspaceId/content-refs/$contentId'
      path: '/$contentId'
      fullPath: '/api/v1/workspaces/$workspaceId/content-refs/$contentId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdContentRefsContentIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdContentRefsRoute
    }
    '/api/v1/workspaces/$workspaceId/messages/$messageId': {
      id: '/api/v1/workspaces/$workspaceId/messages/$messageId'
      path: '/api/v1/workspaces/$workspaceId/messages/$messageId'
      fullPath: '/api/v1/workspaces/$workspaceId/messages/$messageId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdMessagesMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/rooms/$roomId': {
      id: '/api/v1/workspaces/$workspaceId/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/api/v1/workspaces/$workspaceId/rooms/$roomId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRoomIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRoute
    }
    '/api/v1/workspaces/$workspaceId/rooms/reorder': {
      id: '/api/v1/workspaces/$workspaceId/rooms/reorder'
      path: '/reorder'
      fullPath: '/api/v1/workspaces/$workspaceId/rooms/reorder'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsReorderRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksRoute
    }
    '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation': {
      id: '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
      path: '/presentation'
      fullPath: '/api/v1/workspaces/$workspaceId/agents/$agentId/presentation'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute
    }
    '/api/v1/workspaces/$workspaceId/agents/$agentId/profile': {
      id: '/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
      path: '/profile'
      fullPath: '/api/v1/workspaces/$workspaceId/agents/$agentId/profile'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute
    }
    '/api/v1/workspaces/$workspaceId/agents/$agentId/room': {
      id: '/api/v1/workspaces/$workspaceId/agents/$agentId/room'
      path: '/room'
      fullPath: '/api/v1/workspaces/$workspaceId/agents/$agentId/room'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute
    }
    '/api/v1/workspaces/$workspaceId/channels/$channelId/messages': {
      id: '/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
      path: '/messages'
      fullPath: '/api/v1/workspaces/$workspaceId/channels/$channelId/messages'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute
    }
    '/api/v1/workspaces/$workspaceId/channels/$channelId/participants': {
      id: '/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
      path: '/participants'
      fullPath: '/api/v1/workspaces/$workspaceId/channels/$channelId/participants'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute
    }
    '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId': {
      id: '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/api/v1/workspaces/$workspaceId/read-state/channels/$channelId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateRoute
    }
    '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId': {
      id: '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
      path: '/threads/$threadRootMessageId'
      fullPath: '/api/v1/workspaces/$workspaceId/read-state/threads/$threadRootMessageId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
      path: '/archive'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/archive'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
      path: '/artifacts'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/artifacts'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
      path: '/assign'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/assign'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
      path: '/cancel'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/cancel'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
      path: '/complete'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/complete'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
      path: '/conversation'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/conversation'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
      path: '/dependencies'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/dependencies'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
      path: '/queue'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/queue'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/review': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
      path: '/review'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/review'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/room': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
      path: '/room'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/room'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
    '/api/v1/workspaces/$workspaceId/tasks/$taskId/start': {
      id: '/api/v1/workspaces/$workspaceId/tasks/$taskId/start'
      path: '/start'
      fullPath: '/api/v1/workspaces/$workspaceId/tasks/$taskId/start'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute
    }
  }
}

interface ApiWorkspacesWorkspaceIdRouteChildren {
  ApiWorkspacesWorkspaceIdReopenRoute: typeof ApiWorkspacesWorkspaceIdReopenRoute
}

const ApiWorkspacesWorkspaceIdRouteChildren: ApiWorkspacesWorkspaceIdRouteChildren =
  {
    ApiWorkspacesWorkspaceIdReopenRoute: ApiWorkspacesWorkspaceIdReopenRoute,
  }

const ApiWorkspacesWorkspaceIdRouteWithChildren =
  ApiWorkspacesWorkspaceIdRoute._addFileChildren(
    ApiWorkspacesWorkspaceIdRouteChildren,
  )

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesWorkspaceIdRoute: typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  ApiWorkspacesBootstrapRoute: typeof ApiWorkspacesBootstrapRoute
  ApiWorkspacesClaimRoute: typeof ApiWorkspacesClaimRoute
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesWorkspaceIdRoute: ApiWorkspacesWorkspaceIdRouteWithChildren,
  ApiWorkspacesBootstrapRoute: ApiWorkspacesBootstrapRoute,
  ApiWorkspacesClaimRoute: ApiWorkspacesClaimRoute,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

interface ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteChildren {
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute
}

const ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteChildren: ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute:
      ApiV1WorkspacesWorkspaceIdAgentsAgentIdPresentationRoute,
    ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute:
      ApiV1WorkspacesWorkspaceIdAgentsAgentIdProfileRoute,
    ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute:
      ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoomRoute,
  }

const ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdAgentsRouteChildren {
  ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute: typeof ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren
}

const ApiV1WorkspacesWorkspaceIdAgentsRouteChildren: ApiV1WorkspacesWorkspaceIdAgentsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdAgentsAgentIdRoute:
      ApiV1WorkspacesWorkspaceIdAgentsAgentIdRouteWithChildren,
  }

const ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdAgentsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdAgentsRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdArtifactsRouteChildren {
  ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute: typeof ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute
}

const ApiV1WorkspacesWorkspaceIdArtifactsRouteChildren: ApiV1WorkspacesWorkspaceIdArtifactsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute:
      ApiV1WorkspacesWorkspaceIdArtifactsArtifactIdRoute,
  }

const ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdArtifactsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdArtifactsRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteChildren {
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute
}

const ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteChildren: ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute:
      ApiV1WorkspacesWorkspaceIdChannelsChannelIdMessagesRoute,
    ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute:
      ApiV1WorkspacesWorkspaceIdChannelsChannelIdParticipantsRoute,
  }

const ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdChannelsRouteChildren {
  ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute: typeof ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren
}

const ApiV1WorkspacesWorkspaceIdChannelsRouteChildren: ApiV1WorkspacesWorkspaceIdChannelsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdChannelsChannelIdRoute:
      ApiV1WorkspacesWorkspaceIdChannelsChannelIdRouteWithChildren,
  }

const ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdChannelsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdChannelsRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdContentRefsRouteChildren {
  ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute: typeof ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute
}

const ApiV1WorkspacesWorkspaceIdContentRefsRouteChildren: ApiV1WorkspacesWorkspaceIdContentRefsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute:
      ApiV1WorkspacesWorkspaceIdContentRefsContentIdRoute,
  }

const ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdContentRefsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdContentRefsRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdReadStateRouteChildren {
  ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute
  ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute: typeof ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute
}

const ApiV1WorkspacesWorkspaceIdReadStateRouteChildren: ApiV1WorkspacesWorkspaceIdReadStateRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute:
      ApiV1WorkspacesWorkspaceIdReadStateChannelsChannelIdRoute,
    ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute:
      ApiV1WorkspacesWorkspaceIdReadStateThreadsThreadRootMessageIdRoute,
  }

const ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdReadStateRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdReadStateRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdRoomsRouteChildren {
  ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute
  ApiV1WorkspacesWorkspaceIdRoomsReorderRoute: typeof ApiV1WorkspacesWorkspaceIdRoomsReorderRoute
}

const ApiV1WorkspacesWorkspaceIdRoomsRouteChildren: ApiV1WorkspacesWorkspaceIdRoomsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute:
      ApiV1WorkspacesWorkspaceIdRoomsRoomIdRoute,
    ApiV1WorkspacesWorkspaceIdRoomsReorderRoute:
      ApiV1WorkspacesWorkspaceIdRoomsReorderRoute,
  }

const ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdRoomsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdRoomsRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteChildren {
  ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute
  ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute
}

const ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteChildren: ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdArchiveRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdArtifactsRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdAssignRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdCancelRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdCompleteRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdConversationRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdDependenciesRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdQueueRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdReviewRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdRoomRoute,
    ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdStartRoute,
  }

const ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteChildren,
  )

interface ApiV1WorkspacesWorkspaceIdTasksRouteChildren {
  ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute: typeof ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren
}

const ApiV1WorkspacesWorkspaceIdTasksRouteChildren: ApiV1WorkspacesWorkspaceIdTasksRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdTasksTaskIdRoute:
      ApiV1WorkspacesWorkspaceIdTasksTaskIdRouteWithChildren,
  }

const ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdTasksRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdTasksRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSceneEditorRoute: ApiSceneEditorRoute,
  ApiWebEntryRoute: ApiWebEntryRoute,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMarketplaceCatalogRoute: ApiMarketplaceCatalogRoute,
  ApiMarketplaceInstallRoute: ApiMarketplaceInstallRoute,
  ApiMarketplaceInstallPlanRoute: ApiMarketplaceInstallPlanRoute,
  ApiTelemetryScenePerformanceRoute: ApiTelemetryScenePerformanceRoute,
  AuthDesktopCompleteRoute: AuthDesktopCompleteRoute,
  ApiAuthDesktopAuthorizeRoute: ApiAuthDesktopAuthorizeRoute,
  ApiAuthDesktopExchangeRoute: ApiAuthDesktopExchangeRoute,
  ApiAuthDesktopLogoutRoute: ApiAuthDesktopLogoutRoute,
  ApiAuthDesktopRefreshRoute: ApiAuthDesktopRefreshRoute,
  ApiAuthDesktopRevokeRoute: ApiAuthDesktopRevokeRoute,
  ApiV1WorkspacesWorkspaceIdAgentsRoute:
    ApiV1WorkspacesWorkspaceIdAgentsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdArtifactsRoute:
    ApiV1WorkspacesWorkspaceIdArtifactsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdChannelsRoute:
    ApiV1WorkspacesWorkspaceIdChannelsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdContentRefsRoute:
    ApiV1WorkspacesWorkspaceIdContentRefsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdReadStateRoute:
    ApiV1WorkspacesWorkspaceIdReadStateRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdRoomsRoute:
    ApiV1WorkspacesWorkspaceIdRoomsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdSearchRoute: ApiV1WorkspacesWorkspaceIdSearchRoute,
  ApiV1WorkspacesWorkspaceIdTasksRoute:
    ApiV1WorkspacesWorkspaceIdTasksRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute:
    ApiV1WorkspacesWorkspaceIdMessagesMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
