// Generated from the character wearable package.
import type { CharacterPartOption } from "./customization";

export const generatedCharacterParts: readonly CharacterPartOption[] = [
  { id: "body-body-09", label: "Body 09", slot: "body", file: "body/Body_09.glb" },
  { id: "body-body-08", label: "Body 08", slot: "body", file: "body/Body_08.glb" },
  { id: "body-body-06", label: "Body 06", slot: "body", file: "body/Body_06.glb" },
  { id: "body-body-12", label: "Body 12", slot: "body", file: "body/Body_12.glb" },
  { id: "body-body-13", label: "Body 13", slot: "body", file: "body/Body_13.glb" },
  { id: "body-body-07", label: "Body 07", slot: "body", file: "body/Body_07.glb" },
  { id: "body-body-11", label: "Body 11", slot: "body", file: "body/Body_11.glb" },
  { id: "body-body-05", label: "Body 05", slot: "body", file: "body/Body_05.glb" },
  { id: "body-body-04", label: "Body 04", slot: "body", file: "body/Body_04.glb" },
  { id: "body-body-10", label: "Body 10", slot: "body", file: "body/Body_10.glb" },
  { id: "body-body-14", label: "Body 14", slot: "body", file: "body/Body_14.glb" },
  { id: "body-body-01", label: "Body 01", slot: "body", file: "body/Body_01.glb" },
  { id: "body-body-15", label: "Body 15", slot: "body", file: "body/Body_15.glb" },
  { id: "body-body-03", label: "Body 03", slot: "body", file: "body/Body_03.glb" },
  { id: "body-body-16", label: "Body 16", slot: "body", file: "body/Body_16.glb" },
  { id: "body-body-02", label: "Body 02", slot: "body", file: "body/Body_02.glb" },
  {
    id: "face-female-emotion-evil-02",
    label: "Female Emotion Evil 02",
    slot: "face",
    file: "face/Female_Emotion_Evil_02.glb",
  },
  {
    id: "face-male-emotion-sad-02",
    label: "Male Emotion Sad 02",
    slot: "face",
    file: "face/Male_Emotion_Sad_02.glb",
  },
  {
    id: "face-female-emotion-angry-02",
    label: "Female Emotion Angry 02",
    slot: "face",
    file: "face/Female_Emotion_Angry_02.glb",
  },
  {
    id: "face-female-emotion-evil-01",
    label: "Female Emotion Evil 01",
    slot: "face",
    file: "face/Female_Emotion_Evil_01.glb",
  },
  {
    id: "face-male-emotion-sad-01",
    label: "Male Emotion Sad 01",
    slot: "face",
    file: "face/Male_Emotion_Sad_01.glb",
  },
  {
    id: "face-female-emotion-angry-01",
    label: "Female Emotion Angry 01",
    slot: "face",
    file: "face/Female_Emotion_Angry_01.glb",
  },
  {
    id: "face-male-emotion-tongue-01",
    label: "Male Emotion Tongue 01",
    slot: "face",
    file: "face/Male_Emotion_Tongue_01.glb",
  },
  {
    id: "face-male-emotion-love-01",
    label: "Male Emotion Love 01",
    slot: "face",
    file: "face/Male_Emotion_Love_01.glb",
  },
  {
    id: "face-male-emotion-anger-01",
    label: "Male Emotion Anger 01",
    slot: "face",
    file: "face/Male_Emotion_Anger_01.glb",
  },
  {
    id: "face-female-emotion-shout-01",
    label: "Female Emotion Shout 01",
    slot: "face",
    file: "face/Female_Emotion_Shout_01.glb",
  },
  {
    id: "face-female-emotion-tongue-01",
    label: "Female Emotion Tongue 01",
    slot: "face",
    file: "face/Female_Emotion_Tongue_01.glb",
  },
  {
    id: "face-male-emotion-surpriced-01",
    label: "Male Emotion Surpriced 01",
    slot: "face",
    file: "face/Male_Emotion_Surpriced_01.glb",
  },
  {
    id: "face-female-emotion-cry-01",
    label: "Female Emotion Cry 01",
    slot: "face",
    file: "face/Female_Emotion_Cry_01.glb",
  },
  {
    id: "face-female-emotion-love-01",
    label: "Female Emotion Love 01",
    slot: "face",
    file: "face/Female_Emotion_Love_01.glb",
  },
  {
    id: "face-male-emotion-surpriced-02",
    label: "Male Emotion Surpriced 02",
    slot: "face",
    file: "face/Male_Emotion_Surpriced_02.glb",
  },
  {
    id: "face-male-emotion-usual-01",
    label: "Male Emotion Usual 01",
    slot: "face",
    file: "face/Male_Emotion_Usual_01.glb",
  },
  {
    id: "face-male-emotion-happy-01",
    label: "Male Emotion Happy 01",
    slot: "face",
    file: "face/Male_Emotion_Happy_01.glb",
  },
  {
    id: "face-male-emotion-evil-02",
    label: "Male Emotion Evil 02",
    slot: "face",
    file: "face/Male_Emotion_Evil_02.glb",
  },
  {
    id: "face-male-emotion-usual-02",
    label: "Male Emotion Usual 02",
    slot: "face",
    file: "face/Male_Emotion_Usual_02.glb",
  },
  {
    id: "face-male-emotion-happy-02",
    label: "Male Emotion Happy 02",
    slot: "face",
    file: "face/Male_Emotion_Happy_02.glb",
  },
  {
    id: "face-male-emotion-evil-01",
    label: "Male Emotion Evil 01",
    slot: "face",
    file: "face/Male_Emotion_Evil_01.glb",
  },
  {
    id: "face-male-emotion-angry-01",
    label: "Male Emotion Angry 01",
    slot: "face",
    file: "face/Male_Emotion_Angry_01.glb",
  },
  {
    id: "face-male-emotion-angry-02",
    label: "Male Emotion Angry 02",
    slot: "face",
    file: "face/Male_Emotion_Angry_02.glb",
  },
  {
    id: "face-female-emotion-neutral-02",
    label: "Female Emotion Neutral 02",
    slot: "face",
    file: "face/Female_Emotion_Neutral_02.glb",
  },
  {
    id: "face-male-emotion-cry-01",
    label: "Male Emotion Cry 01",
    slot: "face",
    file: "face/Male_Emotion_Cry_01.glb",
  },
  {
    id: "face-male-emotion-confuse-01",
    label: "Male Emotion Confuse 01",
    slot: "face",
    file: "face/Male_Emotion_Confuse_01.glb",
  },
  {
    id: "face-female-emotion-anger-01",
    label: "Female Emotion Anger 01",
    slot: "face",
    file: "face/Female_Emotion_Anger_01.glb",
  },
  {
    id: "face-female-emotion-neutral-01",
    label: "Female Emotion Neutral 01",
    slot: "face",
    file: "face/Female_Emotion_Neutral_01.glb",
  },
  {
    id: "face-male-emotion-shout-01",
    label: "Male Emotion Shout 01",
    slot: "face",
    file: "face/Male_Emotion_Shout_01.glb",
  },
  {
    id: "face-female-emotion-usual-02",
    label: "Female Emotion Usual 02",
    slot: "face",
    file: "face/Female_Emotion_Usual_02.glb",
  },
  {
    id: "face-male-emotion-neutral-02",
    label: "Male Emotion Neutral 02",
    slot: "face",
    file: "face/Male_Emotion_Neutral_02.glb",
  },
  {
    id: "face-female-emotion-happy-02",
    label: "Female Emotion Happy 02",
    slot: "face",
    file: "face/Female_Emotion_Happy_02.glb",
  },
  {
    id: "face-female-emotion-surpriced-02",
    label: "Female Emotion Surpriced 02",
    slot: "face",
    file: "face/Female_Emotion_Surpriced_02.glb",
  },
  {
    id: "face-female-emotion-sad-01",
    label: "Female Emotion Sad 01",
    slot: "face",
    file: "face/Female_Emotion_Sad_01.glb",
  },
  {
    id: "face-female-emotion-usual-01",
    label: "Female Emotion Usual 01",
    slot: "face",
    file: "face/Female_Emotion_Usual_01.glb",
  },
  {
    id: "face-male-emotion-neutral-01",
    label: "Male Emotion Neutral 01",
    slot: "face",
    file: "face/Male_Emotion_Neutral_01.glb",
  },
  {
    id: "face-female-emotion-confuse-01",
    label: "Female Emotion Confuse 01",
    slot: "face",
    file: "face/Female_Emotion_Confuse_01.glb",
  },
  {
    id: "face-female-emotion-happy-01",
    label: "Female Emotion Happy 01",
    slot: "face",
    file: "face/Female_Emotion_Happy_01.glb",
  },
  {
    id: "face-female-emotion-surpriced-01",
    label: "Female Emotion Surpriced 01",
    slot: "face",
    file: "face/Female_Emotion_Surpriced_01.glb",
  },
  {
    id: "face-female-emotion-sad-02",
    label: "Female Emotion Sad 02",
    slot: "face",
    file: "face/Female_Emotion_Sad_02.glb",
  },
  {
    id: "hair-hairstyle-female-08",
    label: "Hairstyle Female 08",
    slot: "hair",
    file: "hair/Hairstyle_Female_08.glb",
  },
  {
    id: "hair-hairstyle-male-09",
    label: "Hairstyle Male 09",
    slot: "hair",
    file: "hair/Hairstyle_Male_09.glb",
  },
  {
    id: "hair-hairstyle-male-08",
    label: "Hairstyle Male 08",
    slot: "hair",
    file: "hair/Hairstyle_Male_08.glb",
  },
  {
    id: "hair-hairstyle-female-09",
    label: "Hairstyle Female 09",
    slot: "hair",
    file: "hair/Hairstyle_Female_09.glb",
  },
  {
    id: "hair-hairstyle-male-18",
    label: "Hairstyle Male 18",
    slot: "hair",
    file: "hair/Hairstyle_Male_18.glb",
  },
  {
    id: "hair-hairstyle-female-02",
    label: "Hairstyle Female 02",
    slot: "hair",
    file: "hair/Hairstyle_Female_02.glb",
  },
  {
    id: "hair-hairstyle-male-03",
    label: "Hairstyle Male 03",
    slot: "hair",
    file: "hair/Hairstyle_Male_03.glb",
  },
  {
    id: "hair-hairstyle-male-17",
    label: "Hairstyle Male 17",
    slot: "hair",
    file: "hair/Hairstyle_Male_17.glb",
  },
  {
    id: "hair-hairstyle-male-16",
    label: "Hairstyle Male 16",
    slot: "hair",
    file: "hair/Hairstyle_Male_16.glb",
  },
  {
    id: "hair-hairstyle-male-02",
    label: "Hairstyle Male 02",
    slot: "hair",
    file: "hair/Hairstyle_Male_02.glb",
  },
  {
    id: "hair-hairstyle-female-03",
    label: "Hairstyle Female 03",
    slot: "hair",
    file: "hair/Hairstyle_Female_03.glb",
  },
  {
    id: "hair-hairstyle-female-01",
    label: "Hairstyle Female 01",
    slot: "hair",
    file: "hair/Hairstyle_Female_01.glb",
  },
  {
    id: "hair-hairstyle-male-14",
    label: "Hairstyle Male 14",
    slot: "hair",
    file: "hair/Hairstyle_Male_14.glb",
  },
  {
    id: "hair-hairstyle-male-01",
    label: "Hairstyle Male 01",
    slot: "hair",
    file: "hair/Hairstyle_Male_01.glb",
  },
  {
    id: "hair-hairstyle-male-15",
    label: "Hairstyle Male 15",
    slot: "hair",
    file: "hair/Hairstyle_Male_15.glb",
  },
  {
    id: "hair-hairstyle-female-04",
    label: "Hairstyle Female 04",
    slot: "hair",
    file: "hair/Hairstyle_Female_04.glb",
  },
  {
    id: "hair-hairstyle-female-10",
    label: "Hairstyle Female 10",
    slot: "hair",
    file: "hair/Hairstyle_Female_10.glb",
  },
  {
    id: "hair-hairstyle-male-11",
    label: "Hairstyle Male 11",
    slot: "hair",
    file: "hair/Hairstyle_Male_11.glb",
  },
  {
    id: "hair-hairstyle-male-05",
    label: "Hairstyle Male 05",
    slot: "hair",
    file: "hair/Hairstyle_Male_05.glb",
  },
  {
    id: "hair-hairstyle-male-04",
    label: "Hairstyle Male 04",
    slot: "hair",
    file: "hair/Hairstyle_Male_04.glb",
  },
  {
    id: "hair-hairstyle-male-10",
    label: "Hairstyle Male 10",
    slot: "hair",
    file: "hair/Hairstyle_Male_10.glb",
  },
  {
    id: "hair-hairstyle-female-11",
    label: "Hairstyle Female 11",
    slot: "hair",
    file: "hair/Hairstyle_Female_11.glb",
  },
  {
    id: "hair-hairstyle-female-05",
    label: "Hairstyle Female 05",
    slot: "hair",
    file: "hair/Hairstyle_Female_05.glb",
  },
  {
    id: "hair-hairstyle-female-07",
    label: "Hairstyle Female 07",
    slot: "hair",
    file: "hair/Hairstyle_Female_07.glb",
  },
  {
    id: "hair-hairstyle-male-06",
    label: "Hairstyle Male 06",
    slot: "hair",
    file: "hair/Hairstyle_Male_06.glb",
  },
  {
    id: "hair-hairstyle-male-12",
    label: "Hairstyle Male 12",
    slot: "hair",
    file: "hair/Hairstyle_Male_12.glb",
  },
  {
    id: "hair-hairstyle-male-13",
    label: "Hairstyle Male 13",
    slot: "hair",
    file: "hair/Hairstyle_Male_13.glb",
  },
  {
    id: "hair-hairstyle-male-07",
    label: "Hairstyle Male 07",
    slot: "hair",
    file: "hair/Hairstyle_Male_07.glb",
  },
  {
    id: "hair-hairstyle-female-06",
    label: "Hairstyle Female 06",
    slot: "hair",
    file: "hair/Hairstyle_Female_06.glb",
  },
  {
    id: "hair-hairstyle-female-12",
    label: "Hairstyle Female 12",
    slot: "hair",
    file: "hair/Hairstyle_Female_12.glb",
  },
  { id: "hat-hat-41", label: "Hat 41", slot: "hat", file: "hat/Hat_41.glb" },
  { id: "hat-hat-55", label: "Hat 55", slot: "hat", file: "hat/Hat_55.glb" },
  { id: "hat-hat-54", label: "Hat 54", slot: "hat", file: "hat/Hat_54.glb" },
  { id: "hat-hat-40", label: "Hat 40", slot: "hat", file: "hat/Hat_40.glb" },
  { id: "hat-hat-56", label: "Hat 56", slot: "hat", file: "hat/Hat_56.glb" },
  { id: "hat-hat-42", label: "Hat 42", slot: "hat", file: "hat/Hat_42.glb" },
  { id: "hat-hat-43", label: "Hat 43", slot: "hat", file: "hat/Hat_43.glb" },
  { id: "hat-hat-57", label: "Hat 57", slot: "hat", file: "hat/Hat_57.glb" },
  { id: "hat-hat-53", label: "Hat 53", slot: "hat", file: "hat/Hat_53.glb" },
  { id: "hat-hat-47", label: "Hat 47", slot: "hat", file: "hat/Hat_47.glb" },
  { id: "hat-hat-46", label: "Hat 46", slot: "hat", file: "hat/Hat_46.glb" },
  { id: "hat-hat-52", label: "Hat 52", slot: "hat", file: "hat/Hat_52.glb" },
  { id: "hat-hat-44", label: "Hat 44", slot: "hat", file: "hat/Hat_44.glb" },
  { id: "hat-hat-50", label: "Hat 50", slot: "hat", file: "hat/Hat_50.glb" },
  { id: "hat-hat-51", label: "Hat 51", slot: "hat", file: "hat/Hat_51.glb" },
  { id: "hat-hat-45", label: "Hat 45", slot: "hat", file: "hat/Hat_45.glb" },
  { id: "hat-hat-22", label: "Hat 22", slot: "hat", file: "hat/Hat_22.glb" },
  { id: "hat-hat-36", label: "Hat 36", slot: "hat", file: "hat/Hat_36.glb" },
  { id: "hat-hat-37", label: "Hat 37", slot: "hat", file: "hat/Hat_37.glb" },
  { id: "hat-hat-23", label: "Hat 23", slot: "hat", file: "hat/Hat_23.glb" },
  { id: "hat-hat-09", label: "Hat 09", slot: "hat", file: "hat/Hat_09.glb" },
  { id: "hat-hat-35", label: "Hat 35", slot: "hat", file: "hat/Hat_35.glb" },
  { id: "hat-hat-21", label: "Hat 21", slot: "hat", file: "hat/Hat_21.glb" },
  { id: "hat-hat-20", label: "Hat 20", slot: "hat", file: "hat/Hat_20.glb" },
  { id: "hat-hat-34", label: "Hat 34", slot: "hat", file: "hat/Hat_34.glb" },
  { id: "hat-hat-08", label: "Hat 08", slot: "hat", file: "hat/Hat_08.glb" },
  { id: "hat-hat-30", label: "Hat 30", slot: "hat", file: "hat/Hat_30.glb" },
  { id: "hat-hat-24", label: "Hat 24", slot: "hat", file: "hat/Hat_24.glb" },
  { id: "hat-hat-18", label: "Hat 18", slot: "hat", file: "hat/Hat_18.glb" },
  { id: "hat-hat-19", label: "Hat 19", slot: "hat", file: "hat/Hat_19.glb" },
  { id: "hat-hat-25", label: "Hat 25", slot: "hat", file: "hat/Hat_25.glb" },
  { id: "hat-hat-31", label: "Hat 31", slot: "hat", file: "hat/Hat_31.glb" },
  { id: "hat-hat-27", label: "Hat 27", slot: "hat", file: "hat/Hat_27.glb" },
  { id: "hat-hat-33", label: "Hat 33", slot: "hat", file: "hat/Hat_33.glb" },
  { id: "hat-hat-32", label: "Hat 32", slot: "hat", file: "hat/Hat_32.glb" },
  { id: "hat-hat-26", label: "Hat 26", slot: "hat", file: "hat/Hat_26.glb" },
  { id: "hat-hat-03", label: "Hat 03", slot: "hat", file: "hat/Hat_03.glb" },
  { id: "hat-hat-17", label: "Hat 17", slot: "hat", file: "hat/Hat_17.glb" },
  { id: "hat-hat-16", label: "Hat 16", slot: "hat", file: "hat/Hat_16.glb" },
  { id: "hat-hat-02", label: "Hat 02", slot: "hat", file: "hat/Hat_02.glb" },
  { id: "hat-hat-28", label: "Hat 28", slot: "hat", file: "hat/Hat_28.glb" },
  { id: "hat-hat-14", label: "Hat 14", slot: "hat", file: "hat/Hat_14.glb" },
  { id: "hat-hat-01", label: "Hat 01", slot: "hat", file: "hat/Hat_01.glb" },
  { id: "hat-hat-15", label: "Hat 15", slot: "hat", file: "hat/Hat_15.glb" },
  { id: "hat-hat-29", label: "Hat 29", slot: "hat", file: "hat/Hat_29.glb" },
  { id: "hat-hat-11", label: "Hat 11", slot: "hat", file: "hat/Hat_11.glb" },
  { id: "hat-hat-05", label: "Hat 05", slot: "hat", file: "hat/Hat_05.glb" },
  { id: "hat-hat-39", label: "Hat 39", slot: "hat", file: "hat/Hat_39.glb" },
  { id: "hat-hat-38", label: "Hat 38", slot: "hat", file: "hat/Hat_38.glb" },
  { id: "hat-hat-04", label: "Hat 04", slot: "hat", file: "hat/Hat_04.glb" },
  { id: "hat-hat-10", label: "Hat 10", slot: "hat", file: "hat/Hat_10.glb" },
  { id: "hat-hat-06", label: "Hat 06", slot: "hat", file: "hat/Hat_06.glb" },
  { id: "hat-hat-12", label: "Hat 12", slot: "hat", file: "hat/Hat_12.glb" },
  { id: "hat-hat-13", label: "Hat 13", slot: "hat", file: "hat/Hat_13.glb" },
  { id: "hat-hat-07", label: "Hat 07", slot: "hat", file: "hat/Hat_07.glb" },
  { id: "hat-hat-48", label: "Hat 48", slot: "hat", file: "hat/Hat_48.glb" },
  { id: "hat-hat-49", label: "Hat 49", slot: "hat", file: "hat/Hat_49.glb" },
  { id: "hat-hat-59", label: "Hat 59", slot: "hat", file: "hat/Hat_59.glb" },
  { id: "hat-hat-58", label: "Hat 58", slot: "hat", file: "hat/Hat_58.glb" },
  { id: "costume-12-02", label: "Costume 12 02", slot: "costume", file: "costume/Costume_12_02.glb" },
  { id: "top-outfit-07", label: "Outfit 07", slot: "top", file: "top/Outfit_07.glb" },
  { id: "top-outwear-25", label: "Outwear 25", slot: "top", file: "top/Outwear_25.glb" },
  { id: "top-outwear-31", label: "Outwear 31", slot: "top", file: "top/Outwear_31.glb" },
  { id: "top-outwear-19", label: "Outwear 19", slot: "top", file: "top/Outwear_19.glb" },
  { id: "costume-4-04", label: "Costume 4 04", slot: "costume", file: "costume/Costume_4_04.glb" },
  { id: "top-outwear-18", label: "Outwear 18", slot: "top", file: "top/Outwear_18.glb" },
  { id: "top-outwear-30", label: "Outwear 30", slot: "top", file: "top/Outwear_30.glb" },
  { id: "top-outwear-24", label: "Outwear 24", slot: "top", file: "top/Outwear_24.glb" },
  { id: "costume-6-01", label: "Costume 6 01", slot: "costume", file: "costume/Costume_6_01.glb" },
  { id: "top-outfit-06", label: "Outfit 06", slot: "top", file: "top/Outfit_06.glb" },
  { id: "costume-12-03", label: "Costume 12 03", slot: "costume", file: "costume/Costume_12_03.glb" },
  { id: "costume-12-01", label: "Costume 12 01", slot: "costume", file: "costume/Costume_12_01.glb" },
  { id: "top-outfit-04", label: "Outfit 04", slot: "top", file: "top/Outfit_04.glb" },
  { id: "top-outwear-32", label: "Outwear 32", slot: "top", file: "top/Outwear_32.glb" },
  { id: "top-outwear-26", label: "Outwear 26", slot: "top", file: "top/Outwear_26.glb" },
  { id: "costume-10-04", label: "Costume 10 04", slot: "costume", file: "costume/Costume_10_04.glb" },
  { id: "costume-10-05", label: "Costume 10 05", slot: "costume", file: "costume/Costume_10_05.glb" },
  { id: "top-outwear-27", label: "Outwear 27", slot: "top", file: "top/Outwear_27.glb" },
  { id: "top-outwear-33", label: "Outwear 33", slot: "top", file: "top/Outwear_33.glb" },
  { id: "costume-6-02", label: "Costume 6 02", slot: "costume", file: "costume/Costume_6_02.glb" },
  { id: "top-outfit-05", label: "Outfit 05", slot: "top", file: "top/Outfit_05.glb" },
  { id: "top-outfit-01", label: "Outfit 01", slot: "top", file: "top/Outfit_01.glb" },
  { id: "top-outwear-37", label: "Outwear 37", slot: "top", file: "top/Outwear_37.glb" },
  { id: "top-outwear-23", label: "Outwear 23", slot: "top", file: "top/Outwear_23.glb" },
  { id: "costume-10-01", label: "Costume 10 01", slot: "costume", file: "costume/Costume_10_01.glb" },
  { id: "costume-4-03", label: "Costume 4 03", slot: "costume", file: "costume/Costume_4_03.glb" },
  { id: "costume-4-02", label: "Costume 4 02", slot: "costume", file: "costume/Costume_4_02.glb" },
  { id: "top-outwear-22", label: "Outwear 22", slot: "top", file: "top/Outwear_22.glb" },
  { id: "top-outwear-36", label: "Outwear 36", slot: "top", file: "top/Outwear_36.glb" },
  { id: "costume-8-02", label: "Costume 8 02", slot: "costume", file: "costume/Costume_8_02.glb" },
  { id: "top-outfit-02", label: "Outfit 02", slot: "top", file: "top/Outfit_02.glb" },
  { id: "top-outwear-08", label: "Outwear 08", slot: "top", file: "top/Outwear_08.glb" },
  { id: "top-outwear-20", label: "Outwear 20", slot: "top", file: "top/Outwear_20.glb" },
  { id: "top-outwear-34", label: "Outwear 34", slot: "top", file: "top/Outwear_34.glb" },
  { id: "costume-10-02", label: "Costume 10 02", slot: "costume", file: "costume/Costume_10_02.glb" },
  { id: "costume-4-01", label: "Costume 4 01", slot: "costume", file: "costume/Costume_4_01.glb" },
  { id: "costume-10-03", label: "Costume 10 03", slot: "costume", file: "costume/Costume_10_03.glb" },
  { id: "top-outwear-35", label: "Outwear 35", slot: "top", file: "top/Outwear_35.glb" },
  { id: "top-outwear-21", label: "Outwear 21", slot: "top", file: "top/Outwear_21.glb" },
  { id: "top-outwear-09", label: "Outwear 09", slot: "top", file: "top/Outwear_09.glb" },
  { id: "costume-8-01", label: "Costume 8 01", slot: "costume", file: "costume/Costume_8_01.glb" },
  { id: "top-outfit-03", label: "Outfit 03", slot: "top", file: "top/Outfit_03.glb" },
  { id: "top-outwear-46", label: "Outwear 46", slot: "top", file: "top/Outwear_46.glb" },
  { id: "top-outwear-52", label: "Outwear 52", slot: "top", file: "top/Outwear_52.glb" },
  { id: "costume-14-01", label: "Costume 14 01", slot: "costume", file: "costume/Costume_14_01.glb" },
  { id: "top-outwear-53", label: "Outwear 53", slot: "top", file: "top/Outwear_53.glb" },
  { id: "top-outwear-47", label: "Outwear 47", slot: "top", file: "top/Outwear_47.glb" },
  { id: "top-outwear-51", label: "Outwear 51", slot: "top", file: "top/Outwear_51.glb" },
  { id: "top-outwear-45", label: "Outwear 45", slot: "top", file: "top/Outwear_45.glb" },
  { id: "costume-2-04", label: "Costume 2 04", slot: "costume", file: "costume/Costume_2_04.glb" },
  { id: "costume-14-03", label: "Costume 14 03", slot: "costume", file: "costume/Costume_14_03.glb" },
  { id: "costume-14-02", label: "Costume 14 02", slot: "costume", file: "costume/Costume_14_02.glb" },
  { id: "top-outwear-44", label: "Outwear 44", slot: "top", file: "top/Outwear_44.glb" },
  { id: "top-outwear-50", label: "Outwear 50", slot: "top", file: "top/Outwear_50.glb" },
  { id: "top-outwear-54", label: "Outwear 54", slot: "top", file: "top/Outwear_54.glb" },
  { id: "top-outwear-40", label: "Outwear 40", slot: "top", file: "top/Outwear_40.glb" },
  { id: "costume-2-01", label: "Costume 2 01", slot: "costume", file: "costume/Costume_2_01.glb" },
  { id: "top-outwear-41", label: "Outwear 41", slot: "top", file: "top/Outwear_41.glb" },
  { id: "top-outwear-55", label: "Outwear 55", slot: "top", file: "top/Outwear_55.glb" },
  { id: "top-outwear-43", label: "Outwear 43", slot: "top", file: "top/Outwear_43.glb" },
  { id: "costume-2-02", label: "Costume 2 02", slot: "costume", file: "costume/Costume_2_02.glb" },
  { id: "costume-2-03", label: "Costume 2 03", slot: "costume", file: "costume/Costume_2_03.glb" },
  { id: "top-outwear-56", label: "Outwear 56", slot: "top", file: "top/Outwear_56.glb" },
  { id: "top-outwear-42", label: "Outwear 42", slot: "top", file: "top/Outwear_42.glb" },
  { id: "costume-11-05", label: "Costume 11 05", slot: "costume", file: "costume/Costume_11_05.glb" },
  { id: "costume-7-02", label: "Costume 7 02", slot: "costume", file: "costume/Costume_7_02.glb" },
  { id: "costume-7-03", label: "Costume 7 03", slot: "costume", file: "costume/Costume_7_03.glb" },
  { id: "costume-13-01", label: "Costume 13 01", slot: "costume", file: "costume/Costume_13_01.glb" },
  { id: "costume-11-04", label: "Costume 11 04", slot: "costume", file: "costume/Costume_11_04.glb" },
  { id: "costume-11-06", label: "Costume 11 06", slot: "costume", file: "costume/Costume_11_06.glb" },
  { id: "costume-5-04", label: "Costume 5 04", slot: "costume", file: "costume/Costume_5_04.glb" },
  { id: "costume-9-04", label: "Costume 9 04", slot: "costume", file: "costume/Costume_9_04.glb" },
  { id: "costume-7-01", label: "Costume 7 01", slot: "costume", file: "costume/Costume_7_01.glb" },
  { id: "costume-9-05", label: "Costume 9 05", slot: "costume", file: "costume/Costume_9_05.glb" },
  { id: "costume-13-02", label: "Costume 13 02", slot: "costume", file: "costume/Costume_13_02.glb" },
  { id: "top-outwear-49", label: "Outwear 49", slot: "top", file: "top/Outwear_49.glb" },
  { id: "costume-11-03", label: "Costume 11 03", slot: "costume", file: "costume/Costume_11_03.glb" },
  { id: "costume-5-01", label: "Costume 5 01", slot: "costume", file: "costume/Costume_5_01.glb" },
  { id: "costume-9-01", label: "Costume 9 01", slot: "costume", file: "costume/Costume_9_01.glb" },
  { id: "costume-11-02", label: "Costume 11 02", slot: "costume", file: "costume/Costume_11_02.glb" },
  { id: "top-outwear-48", label: "Outwear 48", slot: "top", file: "top/Outwear_48.glb" },
  { id: "costume-5-02", label: "Costume 5 02", slot: "costume", file: "costume/Costume_5_02.glb" },
  { id: "costume-9-02", label: "Costume 9 02", slot: "costume", file: "costume/Costume_9_02.glb" },
  { id: "costume-9-03", label: "Costume 9 03", slot: "costume", file: "costume/Costume_9_03.glb" },
  { id: "costume-5-03", label: "Costume 5 03", slot: "costume", file: "costume/Costume_5_03.glb" },
  { id: "costume-11-01", label: "Costume 11 01", slot: "costume", file: "costume/Costume_11_01.glb" },
  { id: "top-outwear-04", label: "Outwear 04", slot: "top", file: "top/Outwear_04.glb" },
  { id: "top-outwear-10", label: "Outwear 10", slot: "top", file: "top/Outwear_10.glb" },
  { id: "top-outwear-38", label: "Outwear 38", slot: "top", file: "top/Outwear_38.glb" },
  { id: "costume-3-05", label: "Costume 3 05", slot: "costume", file: "costume/Costume_3_05.glb" },
  { id: "costume-3-04", label: "Costume 3 04", slot: "costume", file: "costume/Costume_3_04.glb" },
  { id: "top-outwear-39", label: "Outwear 39", slot: "top", file: "top/Outwear_39.glb" },
  { id: "top-outwear-11", label: "Outwear 11", slot: "top", file: "top/Outwear_11.glb" },
  { id: "top-outwear-05", label: "Outwear 05", slot: "top", file: "top/Outwear_05.glb" },
  { id: "costume-1-01", label: "Costume 1 01", slot: "costume", file: "costume/Costume_1_01.glb" },
  { id: "costume-1-03", label: "Costume 1 03", slot: "costume", file: "costume/Costume_1_03.glb" },
  { id: "top-outwear-13", label: "Outwear 13", slot: "top", file: "top/Outwear_13.glb" },
  { id: "top-outwear-07", label: "Outwear 07", slot: "top", file: "top/Outwear_07.glb" },
  { id: "top-outwear-06", label: "Outwear 06", slot: "top", file: "top/Outwear_06.glb" },
  { id: "top-outwear-12", label: "Outwear 12", slot: "top", file: "top/Outwear_12.glb" },
  { id: "costume-1-02", label: "Costume 1 02", slot: "costume", file: "costume/Costume_1_02.glb" },
  { id: "top-outfit-08", label: "Outfit 08", slot: "top", file: "top/Outfit_08.glb" },
  { id: "top-outwear-16", label: "Outwear 16", slot: "top", file: "top/Outwear_16.glb" },
  { id: "top-outwear-02", label: "Outwear 02", slot: "top", file: "top/Outwear_02.glb" },
  { id: "costume-3-03", label: "Costume 3 03", slot: "costume", file: "costume/Costume_3_03.glb" },
  { id: "costume-3-02", label: "Costume 3 02", slot: "costume", file: "costume/Costume_3_02.glb" },
  { id: "top-outwear-03", label: "Outwear 03", slot: "top", file: "top/Outwear_03.glb" },
  { id: "top-outwear-17", label: "Outwear 17", slot: "top", file: "top/Outwear_17.glb" },
  { id: "top-outfit-09", label: "Outfit 09", slot: "top", file: "top/Outfit_09.glb" },
  { id: "top-outwear-29", label: "Outwear 29", slot: "top", file: "top/Outwear_29.glb" },
  { id: "top-outwear-01", label: "Outwear 01", slot: "top", file: "top/Outwear_01.glb" },
  { id: "top-outwear-15", label: "Outwear 15", slot: "top", file: "top/Outwear_15.glb" },
  { id: "costume-3-01", label: "Costume 3 01", slot: "costume", file: "costume/Costume_3_01.glb" },
  { id: "top-outwear-14", label: "Outwear 14", slot: "top", file: "top/Outwear_14.glb" },
  { id: "top-outwear-28", label: "Outwear 28", slot: "top", file: "top/Outwear_28.glb" },
  { id: "bottom-pants-09", label: "Pants 09", slot: "bottom", file: "bottom/Pants_09.glb" },
  { id: "bottom-pants-08", label: "Pants 08", slot: "bottom", file: "bottom/Pants_08.glb" },
  { id: "bottom-shorts-01", label: "Shorts 01", slot: "bottom", file: "bottom/Shorts_01.glb" },
  { id: "bottom-shorts-03", label: "Shorts 03", slot: "bottom", file: "bottom/Shorts_03.glb" },
  { id: "bottom-shorts-02", label: "Shorts 02", slot: "bottom", file: "bottom/Shorts_02.glb" },
  { id: "bottom-pants-05", label: "Pants 05", slot: "bottom", file: "bottom/Pants_05.glb" },
  { id: "bottom-pants-11", label: "Pants 11", slot: "bottom", file: "bottom/Pants_11.glb" },
  { id: "bottom-pants-10", label: "Pants 10", slot: "bottom", file: "bottom/Pants_10.glb" },
  { id: "bottom-pants-04", label: "Pants 04", slot: "bottom", file: "bottom/Pants_04.glb" },
  { id: "bottom-pants-12", label: "Pants 12", slot: "bottom", file: "bottom/Pants_12.glb" },
  { id: "bottom-pants-06", label: "Pants 06", slot: "bottom", file: "bottom/Pants_06.glb" },
  { id: "bottom-pants-07", label: "Pants 07", slot: "bottom", file: "bottom/Pants_07.glb" },
  { id: "bottom-pants-13", label: "Pants 13", slot: "bottom", file: "bottom/Pants_13.glb" },
  { id: "bottom-pants-03", label: "Pants 03", slot: "bottom", file: "bottom/Pants_03.glb" },
  { id: "bottom-pants-02", label: "Pants 02", slot: "bottom", file: "bottom/Pants_02.glb" },
  { id: "bottom-pants-14", label: "Pants 14", slot: "bottom", file: "bottom/Pants_14.glb" },
  { id: "bottom-pants-15", label: "Pants 15", slot: "bottom", file: "bottom/Pants_15.glb" },
  { id: "bottom-pants-01", label: "Pants 01", slot: "bottom", file: "bottom/Pants_01.glb" },
  {
    id: "shoes-shoe-slippers-03",
    label: "Shoe Slippers 03",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_03.glb",
  },
  {
    id: "shoes-shoe-slippers-02",
    label: "Shoe Slippers 02",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_02.glb",
  },
  {
    id: "shoes-shoe-slippers-01",
    label: "Shoe Slippers 01",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_01.glb",
  },
  {
    id: "shoes-shoe-slippers-05",
    label: "Shoe Slippers 05",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_05.glb",
  },
  {
    id: "shoes-shoe-slippers-04",
    label: "Shoe Slippers 04",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_04.glb",
  },
  {
    id: "shoes-shoe-slippers-06",
    label: "Shoe Slippers 06",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_06.glb",
  },
  {
    id: "shoes-shoe-slippers-07",
    label: "Shoe Slippers 07",
    slot: "shoes",
    file: "shoes/Shoe_Slippers_07.glb",
  },
  {
    id: "shoes-shoe-sneakers-03",
    label: "Shoe Sneakers 03",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_03.glb",
  },
  {
    id: "shoes-shoe-sneakers-02",
    label: "Shoe Sneakers 02",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_02.glb",
  },
  {
    id: "shoes-shoe-sneakers-14",
    label: "Shoe Sneakers 14",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_14.glb",
  },
  {
    id: "shoes-shoe-sneakers-15",
    label: "Shoe Sneakers 15",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_15.glb",
  },
  {
    id: "shoes-shoe-sneakers-01",
    label: "Shoe Sneakers 01",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_01.glb",
  },
  {
    id: "shoes-shoe-sneakers-05",
    label: "Shoe Sneakers 05",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_05.glb",
  },
  {
    id: "shoes-shoe-sneakers-11",
    label: "Shoe Sneakers 11",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_11.glb",
  },
  {
    id: "shoes-shoe-sneakers-10",
    label: "Shoe Sneakers 10",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_10.glb",
  },
  {
    id: "shoes-shoe-sneakers-04",
    label: "Shoe Sneakers 04",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_04.glb",
  },
  {
    id: "shoes-shoe-sneakers-12",
    label: "Shoe Sneakers 12",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_12.glb",
  },
  {
    id: "shoes-shoe-sneakers-06",
    label: "Shoe Sneakers 06",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_06.glb",
  },
  {
    id: "shoes-shoe-sneakers-07",
    label: "Shoe Sneakers 07",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_07.glb",
  },
  {
    id: "shoes-shoe-sneakers-13",
    label: "Shoe Sneakers 13",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_13.glb",
  },
  {
    id: "shoes-shoe-sneakers-09",
    label: "Shoe Sneakers 09",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_09.glb",
  },
  {
    id: "shoes-shoe-sneakers-08",
    label: "Shoe Sneakers 08",
    slot: "shoes",
    file: "shoes/Shoe_Sneakers_08.glb",
  },
  { id: "socks-socks-03", label: "Socks 03", slot: "socks", file: "socks/Socks_03.glb" },
  { id: "socks-socks-02", label: "Socks 02", slot: "socks", file: "socks/Socks_02.glb" },
  { id: "socks-socks-01", label: "Socks 01", slot: "socks", file: "socks/Socks_01.glb" },
  {
    id: "glasses-glasses-08",
    label: "Glasses 08",
    slot: "glasses",
    file: "glasses/Glasses_08.glb",
  },
  {
    id: "glasses-glasses-20",
    label: "Glasses 20",
    slot: "glasses",
    file: "glasses/Glasses_20.glb",
  },
  {
    id: "glasses-glasses-21",
    label: "Glasses 21",
    slot: "glasses",
    file: "glasses/Glasses_21.glb",
  },
  {
    id: "glasses-glasses-09",
    label: "Glasses 09",
    slot: "glasses",
    file: "glasses/Glasses_09.glb",
  },
  {
    id: "glasses-glasses-19",
    label: "Glasses 19",
    slot: "glasses",
    file: "glasses/Glasses_19.glb",
  },
  {
    id: "glasses-glasses-18",
    label: "Glasses 18",
    slot: "glasses",
    file: "glasses/Glasses_18.glb",
  },
  {
    id: "glasses-glasses-15",
    label: "Glasses 15",
    slot: "glasses",
    file: "glasses/Glasses_15.glb",
  },
  {
    id: "glasses-glasses-01",
    label: "Glasses 01",
    slot: "glasses",
    file: "glasses/Glasses_01.glb",
  },
  {
    id: "glasses-glasses-14",
    label: "Glasses 14",
    slot: "glasses",
    file: "glasses/Glasses_14.glb",
  },
  {
    id: "glasses-glasses-02",
    label: "Glasses 02",
    slot: "glasses",
    file: "glasses/Glasses_02.glb",
  },
  {
    id: "glasses-glasses-16",
    label: "Glasses 16",
    slot: "glasses",
    file: "glasses/Glasses_16.glb",
  },
  {
    id: "glasses-glasses-17",
    label: "Glasses 17",
    slot: "glasses",
    file: "glasses/Glasses_17.glb",
  },
  {
    id: "glasses-glasses-03",
    label: "Glasses 03",
    slot: "glasses",
    file: "glasses/Glasses_03.glb",
  },
  {
    id: "glasses-glasses-07",
    label: "Glasses 07",
    slot: "glasses",
    file: "glasses/Glasses_07.glb",
  },
  {
    id: "glasses-glasses-13",
    label: "Glasses 13",
    slot: "glasses",
    file: "glasses/Glasses_13.glb",
  },
  {
    id: "glasses-glasses-12",
    label: "Glasses 12",
    slot: "glasses",
    file: "glasses/Glasses_12.glb",
  },
  {
    id: "glasses-glasses-06",
    label: "Glasses 06",
    slot: "glasses",
    file: "glasses/Glasses_06.glb",
  },
  {
    id: "glasses-glasses-10",
    label: "Glasses 10",
    slot: "glasses",
    file: "glasses/Glasses_10.glb",
  },
  {
    id: "glasses-glasses-04",
    label: "Glasses 04",
    slot: "glasses",
    file: "glasses/Glasses_04.glb",
  },
  {
    id: "glasses-glasses-05",
    label: "Glasses 05",
    slot: "glasses",
    file: "glasses/Glasses_05.glb",
  },
  {
    id: "glasses-glasses-11",
    label: "Glasses 11",
    slot: "glasses",
    file: "glasses/Glasses_11.glb",
  },
  { id: "gloves-gloves-09", label: "Gloves 09", slot: "gloves", file: "gloves/Gloves_09.glb" },
  { id: "gloves-gloves-08", label: "Gloves 08", slot: "gloves", file: "gloves/Gloves_08.glb" },
  { id: "gloves-gloves-11", label: "Gloves 11", slot: "gloves", file: "gloves/Gloves_11.glb" },
  { id: "gloves-gloves-05", label: "Gloves 05", slot: "gloves", file: "gloves/Gloves_05.glb" },
  { id: "gloves-gloves-04", label: "Gloves 04", slot: "gloves", file: "gloves/Gloves_04.glb" },
  { id: "gloves-gloves-10", label: "Gloves 10", slot: "gloves", file: "gloves/Gloves_10.glb" },
  { id: "gloves-gloves-06", label: "Gloves 06", slot: "gloves", file: "gloves/Gloves_06.glb" },
  { id: "gloves-gloves-12", label: "Gloves 12", slot: "gloves", file: "gloves/Gloves_12.glb" },
  { id: "gloves-gloves-07", label: "Gloves 07", slot: "gloves", file: "gloves/Gloves_07.glb" },
  { id: "gloves-gloves-03", label: "Gloves 03", slot: "gloves", file: "gloves/Gloves_03.glb" },
  { id: "gloves-gloves-02", label: "Gloves 02", slot: "gloves", file: "gloves/Gloves_02.glb" },
  { id: "gloves-gloves-01", label: "Gloves 01", slot: "gloves", file: "gloves/Gloves_01.glb" },
  { id: "ears-ears-14", label: "Ears 14", slot: "ears", file: "ears/Ears_14.glb" },
  { id: "ears-ears-01", label: "Ears 01", slot: "ears", file: "ears/Ears_01.glb" },
  { id: "ears-ears-15", label: "Ears 15", slot: "ears", file: "ears/Ears_15.glb" },
  { id: "ears-ears-03", label: "Ears 03", slot: "ears", file: "ears/Ears_03.glb" },
  {
    id: "accessory-earrings-01",
    label: "Earrings 01",
    slot: "accessory",
    file: "accessory/Earrings_01.glb",
  },
  {
    id: "accessory-pacifier-001",
    label: "Pacifier 001",
    slot: "accessory",
    file: "accessory/Pacifier_001.glb",
  },
  { id: "ears-ears-16", label: "Ears 16", slot: "ears", file: "ears/Ears_16.glb" },
  { id: "ears-ears-02", label: "Ears 02", slot: "ears", file: "ears/Ears_02.glb" },
  { id: "ears-ears-06", label: "Ears 06", slot: "ears", file: "ears/Ears_06.glb" },
  { id: "ears-ears-12", label: "Ears 12", slot: "ears", file: "ears/Ears_12.glb" },
  {
    id: "accessory-beard-01",
    label: "Beard 01",
    slot: "accessory",
    file: "accessory/Beard_01.glb",
  },
  { id: "ears-ears-13", label: "Ears 13", slot: "ears", file: "ears/Ears_13.glb" },
  { id: "ears-ears-07", label: "Ears 07", slot: "ears", file: "ears/Ears_07.glb" },
  { id: "ears-ears-11", label: "Ears 11", slot: "ears", file: "ears/Ears_11.glb" },
  {
    id: "accessory-bandage-01",
    label: "Bandage 01",
    slot: "accessory",
    file: "accessory/Bandage_01.glb",
  },
  { id: "ears-ears-05", label: "Ears 05", slot: "ears", file: "ears/Ears_05.glb" },
  {
    id: "accessory-beard-03",
    label: "Beard 03",
    slot: "accessory",
    file: "accessory/Beard_03.glb",
  },
  {
    id: "accessory-beard-02",
    label: "Beard 02",
    slot: "accessory",
    file: "accessory/Beard_02.glb",
  },
  { id: "ears-ears-04", label: "Ears 04", slot: "ears", file: "ears/Ears_04.glb" },
  { id: "ears-ears-10", label: "Ears 10", slot: "ears", file: "ears/Ears_10.glb" },
  {
    id: "accessory-clown-nose-01",
    label: "Clown Nose 01",
    slot: "accessory",
    file: "accessory/Clown_nose_01.glb",
  },
  {
    id: "accessory-mustache-08",
    label: "Mustache 08",
    slot: "accessory",
    file: "accessory/Mustache_08.glb",
  },
  {
    id: "accessory-mustache-09",
    label: "Mustache 09",
    slot: "accessory",
    file: "accessory/Mustache_09.glb",
  },
  {
    id: "accessory-mustache-02",
    label: "Mustache 02",
    slot: "accessory",
    file: "accessory/Mustache_02.glb",
  },
  {
    id: "accessory-headphones-02",
    label: "Headphones 02",
    slot: "accessory",
    file: "accessory/Headphones_02.glb",
  },
  {
    id: "accessory-mustache-03",
    label: "Mustache 03",
    slot: "accessory",
    file: "accessory/Mustache_03.glb",
  },
  {
    id: "accessory-mustache-01",
    label: "Mustache 01",
    slot: "accessory",
    file: "accessory/Mustache_01.glb",
  },
  {
    id: "accessory-mustache-15",
    label: "Mustache 15",
    slot: "accessory",
    file: "accessory/Mustache_15.glb",
  },
  {
    id: "accessory-mustache-14",
    label: "Mustache 14",
    slot: "accessory",
    file: "accessory/Mustache_14.glb",
  },
  {
    id: "accessory-mustache-04",
    label: "Mustache 04",
    slot: "accessory",
    file: "accessory/Mustache_04.glb",
  },
  {
    id: "accessory-mustache-10",
    label: "Mustache 10",
    slot: "accessory",
    file: "accessory/Mustache_10.glb",
  },
  {
    id: "accessory-mustache-11",
    label: "Mustache 11",
    slot: "accessory",
    file: "accessory/Mustache_11.glb",
  },
  {
    id: "accessory-mustache-05",
    label: "Mustache 05",
    slot: "accessory",
    file: "accessory/Mustache_05.glb",
  },
  {
    id: "accessory-mustache-13",
    label: "Mustache 13",
    slot: "accessory",
    file: "accessory/Mustache_13.glb",
  },
  {
    id: "accessory-mustache-07",
    label: "Mustache 07",
    slot: "accessory",
    file: "accessory/Mustache_07.glb",
  },
  {
    id: "accessory-mustache-06",
    label: "Mustache 06",
    slot: "accessory",
    file: "accessory/Mustache_06.glb",
  },
  {
    id: "accessory-mustache-12",
    label: "Mustache 12",
    slot: "accessory",
    file: "accessory/Mustache_12.glb",
  },
  { id: "ears-ears-09", label: "Ears 09", slot: "ears", file: "ears/Ears_09.glb" },
  { id: "accessory-mask-01", label: "Mask 01", slot: "accessory", file: "accessory/Mask_01.glb" },
  { id: "ears-ears-08", label: "Ears 08", slot: "ears", file: "ears/Ears_08.glb" },
  { id: "accessory-mask-02", label: "Mask 02", slot: "accessory", file: "accessory/Mask_02.glb" },
];
