/**
 * Dev-only lucide-solid surface.
 *
 * The lucide-solid barrel (`lucide-solid`) statically imports the entire icon
 * catalogue (~1,900 modules). In dev that module graph is catastrophic: the
 * browser floods with ~2,100 icon requests per fresh context (7-10s hydration
 * minimum, 30-120s cold), and the SSR environment babel-compiles the full
 * source tree on first render. The dev alias in `apps/web/vite.config.ts`
 * therefore points the bare specifier at THIS module for both environments:
 * deep per-icon imports keep only the icons the app actually renders in the
 * graph, in both the browser and SSR, from the same source modules so
 * hydration structures match (mixing SSR-compiled source with any
 * client-compiled artifact throws "Failed attempt to create new DOM elements
 * during hydration").
 *
 * The `.jsx` extension is deliberate: vite only pre-bundles `.js/.cjs/.mjs/.ts`
 * entries, so the dependency optimizer can never grab this file and inline raw
 * (uncompiled) Solid JSX into a browser chunk. The file contains no JSX. The
 * production build never sees any of this: the alias only exists for
 * `vite serve`, so `vite build` keeps resolving the `solid` condition directly
 * and tree-shakes the barrel as before.
 */
export { default as AlertTriangle } from 'lucide-solid/icons/triangle-alert'
export { default as Archive } from 'lucide-solid/icons/archive'
export { default as ArrowDown } from 'lucide-solid/icons/arrow-down'
export { default as ArrowLeft } from 'lucide-solid/icons/arrow-left'
export { default as ArrowRight } from 'lucide-solid/icons/arrow-right'
export { default as ArrowUp } from 'lucide-solid/icons/arrow-up'
export { default as AtSign } from 'lucide-solid/icons/at-sign'
export { default as BedDouble } from 'lucide-solid/icons/bed-double'
export { default as Bell } from 'lucide-solid/icons/bell'
export { default as Blocks } from 'lucide-solid/icons/blocks'
export { default as BookOpen } from 'lucide-solid/icons/book-open'
export { default as Bot } from 'lucide-solid/icons/bot'
export { default as BotMessageSquare } from 'lucide-solid/icons/bot-message-square'
export { default as Box } from 'lucide-solid/icons/box'
export { default as Briefcase } from 'lucide-solid/icons/briefcase'
export { default as BriefcaseBusiness } from 'lucide-solid/icons/briefcase-business'
export { default as Bug } from 'lucide-solid/icons/bug'
export { default as Camera } from 'lucide-solid/icons/camera'
export { default as Check } from 'lucide-solid/icons/check'
export { default as CheckCheck } from 'lucide-solid/icons/check-check'
export { default as CheckCircle2 } from 'lucide-solid/icons/circle-check'
export { default as CheckIcon } from 'lucide-solid/icons/check'
export { default as ChevronDown } from 'lucide-solid/icons/chevron-down'
export { default as ChevronRight } from 'lucide-solid/icons/chevron-right'
export { default as ChevronRightIcon } from 'lucide-solid/icons/chevron-right'
export { default as ChevronsUp } from 'lucide-solid/icons/chevrons-up'
export { default as ChevronsUpDown } from 'lucide-solid/icons/chevrons-up-down'
export { default as ChevronUp } from 'lucide-solid/icons/chevron-up'
export { default as CircleHelp } from 'lucide-solid/icons/circle-question-mark'
export { default as CircleUserRound } from 'lucide-solid/icons/circle-user-round'
export { default as ClipboardList } from 'lucide-solid/icons/clipboard-list'
export { default as Code2 } from 'lucide-solid/icons/code-xml'
export { default as Columns2 } from 'lucide-solid/icons/columns-2'
export { default as Database } from 'lucide-solid/icons/database'
export { default as DoorOpen } from 'lucide-solid/icons/door-open'
export { default as Download } from 'lucide-solid/icons/download'
export { default as Dumbbell } from 'lucide-solid/icons/dumbbell'
export { default as EllipsisVertical } from 'lucide-solid/icons/ellipsis-vertical'
export { default as ExternalLink } from 'lucide-solid/icons/external-link'
export { default as EyeOff } from 'lucide-solid/icons/eye-off'
export { default as File } from 'lucide-solid/icons/file'
export { default as Files } from 'lucide-solid/icons/files'
export { default as FileText } from 'lucide-solid/icons/file-text'
export { default as Filter } from 'lucide-solid/icons/funnel'
export { default as Focus } from 'lucide-solid/icons/focus'
export { default as Folder } from 'lucide-solid/icons/folder'
export { default as FolderOpen } from 'lucide-solid/icons/folder-open'
export { default as Gamepad2 } from 'lucide-solid/icons/gamepad-2'
export { default as Gauge } from 'lucide-solid/icons/gauge'
export { default as GitBranch } from 'lucide-solid/icons/git-branch'
export { default as GitCommitHorizontal } from 'lucide-solid/icons/git-commit-horizontal'
export { default as Grid3X3 } from 'lucide-solid/icons/grid-3x3'
export { default as GripVertical } from 'lucide-solid/icons/grip-vertical'
export { default as Hash } from 'lucide-solid/icons/hash'
export { default as History } from 'lucide-solid/icons/rotate-ccw-clock'
export { default as Home } from 'lucide-solid/icons/house'
export { default as Inbox } from 'lucide-solid/icons/inbox'
export { default as Info } from 'lucide-solid/icons/info'
export { default as Laptop } from 'lucide-solid/icons/laptop'
export { default as Leaf } from 'lucide-solid/icons/leaf'
export { default as Link2 } from 'lucide-solid/icons/link-2'
export { default as ListTodo } from 'lucide-solid/icons/list-todo'
export { default as LoaderCircle } from 'lucide-solid/icons/loader-circle'
export { default as LockKeyhole } from 'lucide-solid/icons/lock-keyhole'
export { default as LogIn } from 'lucide-solid/icons/log-in'
export { default as LogOut } from 'lucide-solid/icons/log-out'
export { default as MailOpen } from 'lucide-solid/icons/mail-open'
export { default as Map } from 'lucide-solid/icons/map'
export { default as Maximize2 } from 'lucide-solid/icons/maximize-2'
export { default as Megaphone } from 'lucide-solid/icons/megaphone'
export { default as MessageCircle } from 'lucide-solid/icons/message-circle'
export { default as MessageSquare } from 'lucide-solid/icons/message-square'
export { default as MessageSquareReply } from 'lucide-solid/icons/message-square-reply'
export { default as MessageSquareText } from 'lucide-solid/icons/message-square-text'
export { default as MessagesSquare } from 'lucide-solid/icons/messages-square'
export { default as Mic } from 'lucide-solid/icons/mic'
export { default as MicOff } from 'lucide-solid/icons/mic-off'
export { default as Minus } from 'lucide-solid/icons/minus'
export { default as Monitor } from 'lucide-solid/icons/monitor'
export { default as MonitorCog } from 'lucide-solid/icons/monitor-cog'
export { default as MonitorSmartphone } from 'lucide-solid/icons/monitor-smartphone'
export { default as Moon } from 'lucide-solid/icons/moon'
export { default as MousePointerClick } from 'lucide-solid/icons/mouse-pointer-click'
export { default as Music } from 'lucide-solid/icons/music'
export { default as Music2 } from 'lucide-solid/icons/music-2'
export { default as Palette } from 'lucide-solid/icons/palette'
export { default as PanelLeftClose } from 'lucide-solid/icons/panel-left-close'
export { default as PanelLeftOpen } from 'lucide-solid/icons/panel-left-open'
export { default as PanelRightOpen } from 'lucide-solid/icons/panel-right-open'
export { default as PanelsTopLeft } from 'lucide-solid/icons/panels-top-left'
export { default as Paperclip } from 'lucide-solid/icons/paperclip'
export { default as Pencil } from 'lucide-solid/icons/pencil'
export { default as PictureInPicture2 } from 'lucide-solid/icons/picture-in-picture-2'
export { default as Plane } from 'lucide-solid/icons/plane'
export { default as Play } from 'lucide-solid/icons/play'
export { default as Plug } from 'lucide-solid/icons/plug'
export { default as Plus } from 'lucide-solid/icons/plus'
export { default as RefreshCw } from 'lucide-solid/icons/refresh-cw'
export { default as RotateCcw } from 'lucide-solid/icons/rotate-ccw'
export { default as RotateCw } from 'lucide-solid/icons/rotate-cw'
export { default as Save } from 'lucide-solid/icons/save'
export { default as Search } from 'lucide-solid/icons/search'
export { default as Send } from 'lucide-solid/icons/send'
export { default as Settings } from 'lucide-solid/icons/settings'
export { default as Settings2 } from 'lucide-solid/icons/settings-2'
export { default as Shapes } from 'lucide-solid/icons/shapes'
export { default as ShieldAlert } from 'lucide-solid/icons/shield-alert'
export { default as ShieldCheck } from 'lucide-solid/icons/shield-check'
export { default as SlidersHorizontal } from 'lucide-solid/icons/sliders-horizontal'
export { default as Smartphone } from 'lucide-solid/icons/smartphone'
export { default as Sparkles } from 'lucide-solid/icons/sparkles'
export { default as Square } from 'lucide-solid/icons/square'
export { default as Sun } from 'lucide-solid/icons/sun'
export { default as Tablet } from 'lucide-solid/icons/tablet'
export { default as TerminalSquare } from 'lucide-solid/icons/square-terminal'
export { default as Trash2 } from 'lucide-solid/icons/trash'
export { default as UserRound } from 'lucide-solid/icons/user-round'
export { default as UserRoundPen } from 'lucide-solid/icons/user-round-pen'
export { default as Users } from 'lucide-solid/icons/users'
export { default as Utensils } from 'lucide-solid/icons/utensils'
export { default as Wrench } from 'lucide-solid/icons/wrench'
export { default as X } from 'lucide-solid/icons/x'
export { default as ZoomIn } from 'lucide-solid/icons/zoom-in'
export { default as Copy } from 'lucide-solid/icons/copy'
export { default as ZoomOut } from 'lucide-solid/icons/zoom-out'
