// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_session_resumeHarness = {
  operation: 'dev.session.resumeHarness',
  capabilities: ['dev.session.manage'],
  resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
} as const
