// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_repo_credentialRefs = {
  operation: 'dev.repo.credentialRefs',
  capabilities: ['dev.repo.read'],
  resource: null,
} as const
