// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_browser_laneCreate = {
  operation: 'dev.browser.laneCreate',
  capabilities: ['dev.browser.control'],
  resource: null,
} as const
