// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_cleanupPolicy_disable = {
  operation: 'dev.cleanupPolicy.disable',
  capabilities: ['dev.cleanup.approve'],
  resource: { kind: 'cleanup_policy', idField: 'cleanupPolicyId' },
} as const
