// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_device_capabilities = {
  operation: 'dev.device.capabilities',
  capabilities: ['dev.device.read'],
  resource: null,
} as const
