// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_repo_adopt = {
  operation: 'dev.repo.adopt',
  capabilities: ['dev.repo.manage'],
  resource: { kind: 'repository', idField: 'repoId' },
} as const
