// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_gitlab_pullRequestSummary = {
  operation: 'dev.gitlab.pullRequestSummary',
  capabilities: ['dev.gitlab.read'],
  resource: { kind: 'pull_request', idField: 'pullRequestId' },
} as const
