// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_harness_runStatus = {
  operation: 'dev.harness.runStatus',
  capabilities: ['dev.harness.manage'],
  resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
} as const
