// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_capability_snapshot = {
  operation: 'dev.capability.snapshot',
  capabilities: [],
  resource: null,
} as const
