// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_cleanupPolicy_createDraft = {
  operation: 'dev.cleanupPolicy.createDraft',
  capabilities: ['dev.cleanup.approve'],
  resource: null,
} as const
