// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_connections_setGitHosting = {
  operation: 'dev.connections.setGitHosting',
  capabilities: ['dev.repo.manage'],
  resource: null,
} as const
