// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_project_import = {
  operation: 'dev.project.import',
  capabilities: ['dev.project.manage'],
  resource: null,
} as const
