// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_project_update = {
  operation: 'dev.project.update',
  capabilities: ['dev.project.manage'],
  resource: { kind: 'project', idField: 'projectId' },
} as const
