// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_memory_propose = {
  operation: 'dev.memory.propose',
  capabilities: ['dev.memory.propose'],
  resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
} as const
