// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_terminal_shellProfiles = {
  operation: 'dev.terminal.shellProfiles',
  capabilities: ['dev.terminal.attach'],
  resource: null,
} as const
