// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_files_list = {
  operation: 'dev.files.list',
  capabilities: ['dev.files.read'],
  resource: { kind: 'workspace_root', idField: 'worktreeId' },
} as const
