// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_device_start = {
  operation: 'dev.device.start',
  capabilities: ['dev.device.control'],
  resource: { kind: 'device_inventory', idField: 'inventoryId' },
} as const
