// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_git_history = {
  operation: 'dev.git.history',
  capabilities: ['dev.git.read'],
  resource: { kind: 'worktree', idField: 'worktreeId' },
} as const
