// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_browser_diagnostics = {
  operation: 'dev.browser.diagnostics',
  capabilities: ['dev.browser.read'],
  resource: { kind: 'browser_lane', idField: 'browserLaneId' },
} as const
