// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_gitlab_createPullRequest = {
  operation: 'dev.gitlab.createPullRequest',
  capabilities: ['dev.gitlab.write'],
  resource: { kind: 'repository', idField: 'repoId' },
} as const
