// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_connections_setHarnessAccount = {
  operation: 'dev.connections.setHarnessAccount',
  capabilities: ['dev.harness.manage'],
  resource: null,
} as const
