// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_terminal_input = {
  operation: 'dev.terminal.input',
  capabilities: ['dev.terminal.input'],
  resource: { kind: 'terminal', idField: 'terminalId' },
} as const
