// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_harness_preferences = {
  operation: 'dev.harness.preferences',
  capabilities: ['dev.harness.read'],
  resource: null,
} as const
