// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_resources_janitorCommit = {
  operation: 'dev.resources.janitorCommit',
  capabilities: ['dev.resources.janitor'],
  resource: { kind: 'janitor_plan', idField: 'planId' },
} as const
