// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_repo_inspect = {
  operation: 'dev.repo.inspect',
  capabilities: ['dev.repo.read'],
  resource: { kind: 'repository', idField: 'repoId' },
} as const
