// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_summary_workspaces = {
  operation: 'dev.summary.workspaces',
  capabilities: ['dev.summary.read'],
  resource: null,
} as const
