// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_project_bookmarks = {
  operation: 'dev.project.bookmarks',
  capabilities: ['dev.project.read'],
  resource: null,
} as const
