// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_computeruse_laneClose = {
  operation: 'dev.computeruse.laneClose',
  capabilities: ['dev.computeruse.control'],
  resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
} as const
