// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_group_delete = {
  operation: 'dev.group.delete',
  capabilities: ['dev.project.manage'],
  resource: { kind: 'group', idField: 'groupId' },
} as const
