// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_github_pullRequests = {
  operation: 'dev.github.pullRequests',
  capabilities: ['dev.github.read'],
  resource: { kind: 'repository', idField: 'repoId' },
} as const
