// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_worktree_retryBootstrap = {
  operation: 'dev.worktree.retryBootstrap',
  capabilities: ['dev.worktree.manage'],
  resource: { kind: 'worktree', idField: 'worktreeId' },
} as const
