// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_project_scan = {
  operation: 'dev.project.scan',
  capabilities: ['dev.files.read', 'dev.project.read'],
  resource: null,
} as const
