// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_resources_janitorPlan = {
  operation: 'dev.resources.janitorPlan',
  capabilities: ['dev.resources.janitor'],
  resource: null,
} as const
