// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_resources_snapshot = {
  operation: 'dev.resources.snapshot',
  capabilities: ['dev.resources.read'],
  resource: null,
} as const
