// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_device_stop = {
  operation: 'dev.device.stop',
  capabilities: ['dev.device.control'],
  resource: { kind: 'device_session', idField: 'deviceSessionId' },
} as const
