// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_worktree_cleanupJobs = {
  operation: 'dev.worktree.cleanupJobs',
  capabilities: ['dev.resources.read'],
  resource: { kind: 'worktree', idField: 'worktreeId' },
} as const
