// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_github_updatePlan = {
  operation: 'dev.github.updatePlan',
  capabilities: ['dev.github.write'],
  resource: { kind: 'pull_request', idField: 'pullRequestId' },
} as const
