// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_resources_stopCommit = {
  operation: 'dev.resources.stopCommit',
  capabilities: ['dev.resources.stop'],
  resource: { kind: 'process', idField: 'processRecordId' },
} as const
