// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_terminal_create = {
  operation: 'dev.terminal.create',
  capabilities: ['dev.terminal.manage'],
  resource: null,
} as const
