// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_connections_get = {
  operation: 'dev.connections.get',
  capabilities: ['dev.harness.read', 'dev.repo.read'],
  resource: null,
} as const
