// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_group_create = {
  operation: 'dev.group.create',
  capabilities: ['dev.project.manage'],
  resource: null,
} as const
