// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.

export const devOperationMetadataFor_dev_worktree_create = {
  operation: 'dev.worktree.create',
  capabilities: ['dev.worktree.manage'],
  resource: null,
} as const
