import { expect, test } from './fixtures'

test('view switches, query preservation and browser history keep the workspace usable', async ({
  page,
}) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?view=chat&roomDesigner=0&characterDesigner=0&unknown=retained&x=a%26b&x=c%2Bd')
  await expect(page.getByRole('button', { name: 'User settings' })).toBeVisible({ timeout: 20_000 })
  await page.getByRole('button', { name: 'Virtual view', exact: true }).click()
  await expect(page.locator('.workspace-frame--virtual')).toBeVisible()
  await expect(page.getByRole('status', { name: 'Virtual view unavailable' })).toBeVisible()
  await expect.poll(() => new URL(page.url()).searchParams.get('view')).toBe('virtual')
  await page.getByRole('button', { name: 'Chat view', exact: true }).click()
  await expect(page.locator('.workspace-frame--chat')).toBeVisible()
  await expect.poll(() => new URL(page.url()).searchParams.get('view')).toBe('chat')
  await page.goBack()
  await expect(page.locator('.workspace-frame--virtual')).toBeVisible()
  await expect.poll(() => new URL(page.url()).searchParams.get('view')).toBe('virtual')
  await page.goForward()
  await expect(page.locator('.workspace-frame--chat')).toBeVisible()
  await expect.poll(() => new URL(page.url()).searchParams.get('view')).toBe('chat')
  expect(new URL(page.url()).searchParams.getAll('x')).toEqual(['a&b', 'c+d'])
  expect(new URL(page.url()).searchParams.get('unknown')).toBe('retained')
  await page.goto('/?scene=work&view=virtual&roomDesigner=0')
  await expect(page.locator('.workspace-frame--virtual')).toBeVisible()
  await page.goBack()
  await expect(page.locator('.workspace-frame--chat')).toBeVisible()
  const restored = new URL(page.url())
  expect(restored.searchParams.get('view')).toBe('chat')
  expect(restored.searchParams.get('unknown')).toBe('retained')
  expect(restored.searchParams.getAll('x')).toEqual(['a&b', 'c+d'])
  await page.goForward()
  await expect(page.locator('.workspace-frame--virtual')).toBeVisible()
  expect(errors).toEqual([])
})
