// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.
// Browser-safe operation metadata; request DSL and reply schema names stay in the server registry.

export const devOperationMetadata = {
  'dev.browser.annotate': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.attach': {
    capabilities: ['dev.browser.read'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.cookieImportCommit': {
    capabilities: ['dev.browser.cookies'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.cookieImportPlan': {
    capabilities: ['dev.browser.cookies'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.cookieSources': { capabilities: ['dev.browser.cookies'], resource: null },
  'dev.browser.diagnostics': {
    capabilities: ['dev.browser.read'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.input': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.inspect': {
    capabilities: ['dev.browser.read'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.laneClose': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.laneCreate': { capabilities: ['dev.browser.control'], resource: null },
  'dev.browser.lanes': { capabilities: ['dev.browser.read'], resource: null },
  'dev.browser.navigate': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.profilePolicies': { capabilities: ['dev.browser.read'], resource: null },
  'dev.browser.profileReset': {
    capabilities: ['dev.browser.cookies'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.release': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.screenshot': {
    capabilities: ['dev.browser.read'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.takeover': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.targets': {
    capabilities: ['dev.browser.read'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.browser.viewport': {
    capabilities: ['dev.browser.control'],
    resource: { kind: 'browser_lane', idField: 'browserLaneId' },
  },
  'dev.capability.snapshot': { capabilities: [], resource: null },
  'dev.cleanupPolicy.approve': {
    capabilities: ['dev.cleanup.approve'],
    resource: { kind: 'cleanup_policy', idField: 'cleanupPolicyId' },
  },
  'dev.cleanupPolicy.createDraft': { capabilities: ['dev.cleanup.approve'], resource: null },
  'dev.cleanupPolicy.disable': {
    capabilities: ['dev.cleanup.approve'],
    resource: { kind: 'cleanup_policy', idField: 'cleanupPolicyId' },
  },
  'dev.cleanupPolicy.evaluate': {
    capabilities: ['dev.cleanup.approve'],
    resource: { kind: 'cleanup_policy', idField: 'cleanupPolicyId' },
  },
  'dev.cleanupPolicy.list': { capabilities: ['dev.resources.read'], resource: null },
  'dev.computeruse.attach': {
    capabilities: ['dev.computeruse.read'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.computeruse.capabilities': { capabilities: ['dev.computeruse.read'], resource: null },
  'dev.computeruse.consent': {
    capabilities: ['dev.computeruse.control'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.computeruse.input': {
    capabilities: ['dev.computeruse.control'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.computeruse.laneClose': {
    capabilities: ['dev.computeruse.control'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.computeruse.laneCreate': { capabilities: ['dev.computeruse.control'], resource: null },
  'dev.computeruse.lanes': { capabilities: ['dev.computeruse.read'], resource: null },
  'dev.computeruse.release': {
    capabilities: ['dev.computeruse.control'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.computeruse.takeover': {
    capabilities: ['dev.computeruse.control'],
    resource: { kind: 'computeruse_lane', idField: 'computerUseLaneId' },
  },
  'dev.device.attach': {
    capabilities: ['dev.device.read'],
    resource: { kind: 'device_session', idField: 'deviceSessionId' },
  },
  'dev.device.input': {
    capabilities: ['dev.device.control'],
    resource: { kind: 'device_session', idField: 'deviceSessionId' },
  },
  'dev.device.list': { capabilities: ['dev.device.read'], resource: null },
  'dev.device.screenshot': {
    capabilities: ['dev.device.read'],
    resource: { kind: 'device_session', idField: 'deviceSessionId' },
  },
  'dev.device.sessions': { capabilities: ['dev.device.read'], resource: null },
  'dev.device.start': {
    capabilities: ['dev.device.control'],
    resource: { kind: 'device_inventory', idField: 'inventoryId' },
  },
  'dev.device.stop': {
    capabilities: ['dev.device.control'],
    resource: { kind: 'device_session', idField: 'deviceSessionId' },
  },
  'dev.files.copy': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.copyTreeCommit': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.copyTreePlan': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.create': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.delete': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.deleteTreeCommit': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.deleteTreePlan': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.list': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.openExternal': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.read': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.readStream': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.rename': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.renameOverwriteCommit': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.renameOverwritePlan': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.search': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.stat': {
    capabilities: ['dev.files.read'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.write': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.files.writeStream': {
    capabilities: ['dev.files.write'],
    resource: { kind: 'workspace_root', idField: 'worktreeId' },
  },
  'dev.git.checkpoint': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.checkpointPrune': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.commit': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.diff': {
    capabilities: ['dev.git.read'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.discardCommit': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.discardPlan': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.fetch': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.history': {
    capabilities: ['dev.git.read'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.hunkStagingCommit': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.hunkStagingPlan': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.restoreCommit': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.restorePlan': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.stage': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.status': {
    capabilities: ['dev.git.read'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.git.unstage': {
    capabilities: ['dev.git.write'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.github.account': { capabilities: ['dev.github.read'], resource: null },
  'dev.github.checks': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.createPullRequest': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.issues': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.mergeCommit': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.mergePlan': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.milestones': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.pullRequest': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.pullRequests': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.pushCommit': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.pushPlan': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.repository': {
    capabilities: ['dev.github.read'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.github.updateBranchCommit': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.updateBranchPlan': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.updateCommit': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.github.updatePlan': {
    capabilities: ['dev.github.write'],
    resource: { kind: 'pull_request', idField: 'pullRequestId' },
  },
  'dev.group.create': { capabilities: ['dev.project.manage'], resource: null },
  'dev.group.delete': {
    capabilities: ['dev.project.manage'],
    resource: { kind: 'group', idField: 'groupId' },
  },
  'dev.group.list': { capabilities: ['dev.project.read'], resource: null },
  'dev.group.reorder': { capabilities: ['dev.project.manage'], resource: null },
  'dev.group.update': {
    capabilities: ['dev.project.manage'],
    resource: { kind: 'group', idField: 'groupId' },
  },
  'dev.harness.acpClose': {
    capabilities: ['dev.harness.manage'],
    resource: { kind: 'acp_connection', idField: 'acpConnectionId' },
  },
  'dev.harness.acpConnect': {
    capabilities: ['dev.harness.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.harness.acpConnections': { capabilities: ['dev.harness.read'], resource: null },
  'dev.harness.managedPiInstall': { capabilities: ['dev.harness.manage'], resource: null },
  'dev.harness.managedPiStatus': { capabilities: ['dev.harness.read'], resource: null },
  'dev.harness.preferenceReset': { capabilities: ['dev.harness.manage'], resource: null },
  'dev.harness.preferenceUpdate': { capabilities: ['dev.harness.manage'], resource: null },
  'dev.harness.preferences': { capabilities: ['dev.harness.read'], resource: null },
  'dev.harness.runStatus': {
    capabilities: ['dev.harness.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.harness.runs': { capabilities: ['dev.harness.read'], resource: null },
  'dev.project.archive': {
    capabilities: ['dev.project.manage'],
    resource: { kind: 'project', idField: 'projectId' },
  },
  'dev.project.bookmarks': { capabilities: ['dev.project.read'], resource: null },
  'dev.project.clone': { capabilities: ['dev.project.manage', 'dev.repo.manage'], resource: null },
  'dev.project.create': { capabilities: ['dev.project.manage'], resource: null },
  'dev.project.get': {
    capabilities: ['dev.project.read'],
    resource: { kind: 'project', idField: 'projectId' },
  },
  'dev.project.import': { capabilities: ['dev.project.manage'], resource: null },
  'dev.project.list': { capabilities: ['dev.project.read'], resource: null },
  'dev.project.reorder': { capabilities: ['dev.project.manage'], resource: null },
  'dev.project.scan': { capabilities: ['dev.files.read', 'dev.project.read'], resource: null },
  'dev.project.update': {
    capabilities: ['dev.project.manage'],
    resource: { kind: 'project', idField: 'projectId' },
  },
  'dev.repo.adopt': {
    capabilities: ['dev.repo.manage'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.repo.authorize': {
    capabilities: ['dev.repo.manage'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.repo.credentialRefs': { capabilities: ['dev.repo.read'], resource: null },
  'dev.repo.inspect': {
    capabilities: ['dev.repo.read'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.repo.list': { capabilities: ['dev.repo.read'], resource: null },
  'dev.repo.refresh': {
    capabilities: ['dev.repo.manage'],
    resource: { kind: 'repository', idField: 'repoId' },
  },
  'dev.resources.metrics': { capabilities: ['dev.resources.read'], resource: null },
  'dev.resources.ports': { capabilities: ['dev.resources.read'], resource: null },
  'dev.resources.processes': { capabilities: ['dev.resources.read'], resource: null },
  'dev.resources.retainedData': { capabilities: ['dev.resources.read'], resource: null },
  'dev.resources.snapshot': { capabilities: ['dev.resources.read'], resource: null },
  'dev.resources.stopCommit': {
    capabilities: ['dev.resources.stop'],
    resource: { kind: 'process', idField: 'processRecordId' },
  },
  'dev.resources.stopPlan': {
    capabilities: ['dev.resources.stop'],
    resource: { kind: 'process', idField: 'processRecordId' },
  },
  'dev.resources.usage': { capabilities: ['dev.resources.read'], resource: null },
  'dev.session.archive': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.cancelHarness': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.create': { capabilities: ['dev.session.manage'], resource: null },
  'dev.session.events': {
    capabilities: ['dev.session.read'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.get': {
    capabilities: ['dev.session.read'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.launchDefault': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.launchHarness': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.list': { capabilities: ['dev.session.read'], resource: null },
  'dev.session.resumeHarness': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.transferInput': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.session.unarchive': {
    capabilities: ['dev.session.manage'],
    resource: { kind: 'runtime_session', idField: 'runtimeSessionId' },
  },
  'dev.terminal.attach': {
    capabilities: ['dev.terminal.attach'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.checkpoint': {
    capabilities: ['dev.terminal.attach'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.create': { capabilities: ['dev.terminal.manage'], resource: null },
  'dev.terminal.detach': {
    capabilities: ['dev.terminal.attach'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.historyDelete': {
    capabilities: ['dev.terminal.manage'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.input': {
    capabilities: ['dev.terminal.input'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.list': { capabilities: ['dev.terminal.attach'], resource: null },
  'dev.terminal.resize': {
    capabilities: ['dev.terminal.manage'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.search': {
    capabilities: ['dev.terminal.attach'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.shellProfiles': { capabilities: ['dev.terminal.attach'], resource: null },
  'dev.terminal.signal': {
    capabilities: ['dev.terminal.manage'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.terminal.terminate': {
    capabilities: ['dev.terminal.manage'],
    resource: { kind: 'terminal', idField: 'terminalId' },
  },
  'dev.worktree.archive': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.cleanupCommit': {
    capabilities: ['dev.cleanup.approve', 'dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.cleanupJobs': {
    capabilities: ['dev.resources.read'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.cleanupPlan': {
    capabilities: ['dev.cleanup.approve', 'dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.cleanupResume': {
    capabilities: ['dev.cleanup.approve', 'dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.create': { capabilities: ['dev.worktree.manage'], resource: null },
  'dev.worktree.lease': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.list': { capabilities: ['dev.worktree.read'], resource: null },
  'dev.worktree.mergeCommit': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.mergePlan': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.releaseLease': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.retryBootstrap': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
  'dev.worktree.unarchive': {
    capabilities: ['dev.worktree.manage'],
    resource: { kind: 'worktree', idField: 'worktreeId' },
  },
} as const
