// Generated by scripts/generate-dev-runtime-contract.mjs from
// docs/specs/dev-runtime-operations.json. Do not edit by hand.
// Browser-safe operation metadata; request DSL and reply schema names stay in the server registry.

import * as operationMetadata from './dev-runtime-operation-metadata/index'

export * from './dev-runtime-operation-metadata/index'

export const devOperationMetadata = {
  'dev.browser.annotate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_annotate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_annotate.resource,
  },
  'dev.browser.attach': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_attach.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_attach.resource,
  },
  'dev.browser.cookieImportCommit': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_browser_cookieImportCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_cookieImportCommit.resource,
  },
  'dev.browser.cookieImportPlan': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_browser_cookieImportPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_cookieImportPlan.resource,
  },
  'dev.browser.cookieSources': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_cookieSources.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_cookieSources.resource,
  },
  'dev.browser.diagnostics': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_diagnostics.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_diagnostics.resource,
  },
  'dev.browser.input': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_input.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_input.resource,
  },
  'dev.browser.inspect': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_inspect.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_inspect.resource,
  },
  'dev.browser.laneClose': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_laneClose.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_laneClose.resource,
  },
  'dev.browser.laneCreate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_laneCreate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_laneCreate.resource,
  },
  'dev.browser.lanes': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_lanes.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_lanes.resource,
  },
  'dev.browser.navigate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_navigate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_navigate.resource,
  },
  'dev.browser.profilePolicies': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_browser_profilePolicies.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_profilePolicies.resource,
  },
  'dev.browser.profileReset': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_profileReset.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_profileReset.resource,
  },
  'dev.browser.release': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_release.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_release.resource,
  },
  'dev.browser.screenshot': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_screenshot.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_screenshot.resource,
  },
  'dev.browser.takeover': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_takeover.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_takeover.resource,
  },
  'dev.browser.targets': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_targets.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_targets.resource,
  },
  'dev.browser.viewport': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_browser_viewport.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_browser_viewport.resource,
  },
  'dev.capability.snapshot': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_capability_snapshot.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_capability_snapshot.resource,
  },
  'dev.cleanupPolicy.approve': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_approve.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_approve.resource,
  },
  'dev.cleanupPolicy.createDraft': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_createDraft.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_createDraft.resource,
  },
  'dev.cleanupPolicy.disable': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_disable.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_disable.resource,
  },
  'dev.cleanupPolicy.evaluate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_evaluate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_evaluate.resource,
  },
  'dev.cleanupPolicy.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_cleanupPolicy_list.resource,
  },
  'dev.computeruse.attach': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_attach.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_attach.resource,
  },
  'dev.computeruse.capabilities': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_computeruse_capabilities.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_capabilities.resource,
  },
  'dev.computeruse.consent': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_consent.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_consent.resource,
  },
  'dev.computeruse.input': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_input.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_input.resource,
  },
  'dev.computeruse.laneClose': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_laneClose.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_laneClose.resource,
  },
  'dev.computeruse.laneCreate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_laneCreate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_laneCreate.resource,
  },
  'dev.computeruse.lanes': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_lanes.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_lanes.resource,
  },
  'dev.computeruse.release': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_release.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_release.resource,
  },
  'dev.computeruse.takeover': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_computeruse_takeover.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_computeruse_takeover.resource,
  },
  'dev.device.attach': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_attach.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_attach.resource,
  },
  'dev.device.input': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_input.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_input.resource,
  },
  'dev.device.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_list.resource,
  },
  'dev.device.screenshot': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_screenshot.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_screenshot.resource,
  },
  'dev.device.sessions': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_sessions.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_sessions.resource,
  },
  'dev.device.start': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_start.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_start.resource,
  },
  'dev.device.stop': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_device_stop.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_device_stop.resource,
  },
  'dev.files.copy': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_copy.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_copy.resource,
  },
  'dev.files.copyTreeCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_copyTreeCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_copyTreeCommit.resource,
  },
  'dev.files.copyTreePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_copyTreePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_copyTreePlan.resource,
  },
  'dev.files.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_create.resource,
  },
  'dev.files.delete': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_delete.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_delete.resource,
  },
  'dev.files.deleteTreeCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_deleteTreeCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_deleteTreeCommit.resource,
  },
  'dev.files.deleteTreePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_deleteTreePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_deleteTreePlan.resource,
  },
  'dev.files.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_list.resource,
  },
  'dev.files.openExternal': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_openExternal.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_openExternal.resource,
  },
  'dev.files.read': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_read.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_read.resource,
  },
  'dev.files.readStream': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_readStream.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_readStream.resource,
  },
  'dev.files.rename': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_rename.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_rename.resource,
  },
  'dev.files.renameOverwriteCommit': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_files_renameOverwriteCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_renameOverwriteCommit.resource,
  },
  'dev.files.renameOverwritePlan': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_files_renameOverwritePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_renameOverwritePlan.resource,
  },
  'dev.files.search': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_search.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_search.resource,
  },
  'dev.files.stat': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_stat.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_stat.resource,
  },
  'dev.files.write': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_write.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_write.resource,
  },
  'dev.files.writeStream': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_files_writeStream.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_files_writeStream.resource,
  },
  'dev.git.checkpoint': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_checkpoint.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_checkpoint.resource,
  },
  'dev.git.checkpointPrune': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_checkpointPrune.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_checkpointPrune.resource,
  },
  'dev.git.commit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_commit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_commit.resource,
  },
  'dev.git.diff': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_diff.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_diff.resource,
  },
  'dev.git.discardCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_discardCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_discardCommit.resource,
  },
  'dev.git.discardPlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_discardPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_discardPlan.resource,
  },
  'dev.git.fetch': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_fetch.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_fetch.resource,
  },
  'dev.git.history': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_history.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_history.resource,
  },
  'dev.git.hunkStagingCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_hunkStagingCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_hunkStagingCommit.resource,
  },
  'dev.git.hunkStagingPlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_hunkStagingPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_hunkStagingPlan.resource,
  },
  'dev.git.restoreCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_restoreCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_restoreCommit.resource,
  },
  'dev.git.restorePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_restorePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_restorePlan.resource,
  },
  'dev.git.stage': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_stage.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_stage.resource,
  },
  'dev.git.status': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_status.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_status.resource,
  },
  'dev.git.unstage': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_git_unstage.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_git_unstage.resource,
  },
  'dev.github.account': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_account.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_account.resource,
  },
  'dev.github.checks': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_checks.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_checks.resource,
  },
  'dev.github.createPullRequest': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_github_createPullRequest.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_createPullRequest.resource,
  },
  'dev.github.issues': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_issues.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_issues.resource,
  },
  'dev.github.mergeCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_mergeCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_mergeCommit.resource,
  },
  'dev.github.mergePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_mergePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_mergePlan.resource,
  },
  'dev.github.milestones': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_milestones.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_milestones.resource,
  },
  'dev.github.pullRequest': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_pullRequest.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_pullRequest.resource,
  },
  'dev.github.pullRequests': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_pullRequests.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_pullRequests.resource,
  },
  'dev.github.pushCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_pushCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_pushCommit.resource,
  },
  'dev.github.pushPlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_pushPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_pushPlan.resource,
  },
  'dev.github.repository': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_repository.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_repository.resource,
  },
  'dev.github.updateBranchCommit': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_github_updateBranchCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_updateBranchCommit.resource,
  },
  'dev.github.updateBranchPlan': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_github_updateBranchPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_updateBranchPlan.resource,
  },
  'dev.github.updateCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_updateCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_updateCommit.resource,
  },
  'dev.github.updatePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_github_updatePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_github_updatePlan.resource,
  },
  'dev.group.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_group_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_group_create.resource,
  },
  'dev.group.delete': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_group_delete.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_group_delete.resource,
  },
  'dev.group.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_group_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_group_list.resource,
  },
  'dev.group.reorder': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_group_reorder.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_group_reorder.resource,
  },
  'dev.group.update': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_group_update.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_group_update.resource,
  },
  'dev.harness.acpClose': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_acpClose.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_acpClose.resource,
  },
  'dev.harness.acpConnect': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_acpConnect.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_acpConnect.resource,
  },
  'dev.harness.acpConnections': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_acpConnections.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_acpConnections.resource,
  },
  'dev.harness.managedPiInstall': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_harness_managedPiInstall.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_managedPiInstall.resource,
  },
  'dev.harness.managedPiStatus': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_harness_managedPiStatus.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_managedPiStatus.resource,
  },
  'dev.harness.preferenceReset': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_harness_preferenceReset.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_preferenceReset.resource,
  },
  'dev.harness.preferenceUpdate': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_harness_preferenceUpdate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_preferenceUpdate.resource,
  },
  'dev.harness.preferences': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_preferences.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_preferences.resource,
  },
  'dev.harness.runStatus': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_runStatus.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_runStatus.resource,
  },
  'dev.harness.runs': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_harness_runs.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_harness_runs.resource,
  },
  'dev.project.archive': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_archive.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_archive.resource,
  },
  'dev.project.bookmarks': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_bookmarks.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_bookmarks.resource,
  },
  'dev.project.clone': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_clone.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_clone.resource,
  },
  'dev.project.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_create.resource,
  },
  'dev.project.get': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_get.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_get.resource,
  },
  'dev.project.import': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_import.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_import.resource,
  },
  'dev.project.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_list.resource,
  },
  'dev.project.reorder': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_reorder.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_reorder.resource,
  },
  'dev.project.scan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_scan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_scan.resource,
  },
  'dev.project.update': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_project_update.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_project_update.resource,
  },
  'dev.repo.adopt': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_adopt.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_adopt.resource,
  },
  'dev.repo.authorize': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_authorize.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_authorize.resource,
  },
  'dev.repo.credentialRefs': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_credentialRefs.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_credentialRefs.resource,
  },
  'dev.repo.inspect': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_inspect.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_inspect.resource,
  },
  'dev.repo.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_list.resource,
  },
  'dev.repo.refresh': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_repo_refresh.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_repo_refresh.resource,
  },
  'dev.resources.metrics': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_metrics.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_metrics.resource,
  },
  'dev.resources.ports': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_ports.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_ports.resource,
  },
  'dev.resources.processes': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_processes.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_processes.resource,
  },
  'dev.resources.retainedData': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_retainedData.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_retainedData.resource,
  },
  'dev.resources.snapshot': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_snapshot.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_snapshot.resource,
  },
  'dev.resources.stopCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_stopCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_stopCommit.resource,
  },
  'dev.resources.stopPlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_stopPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_stopPlan.resource,
  },
  'dev.resources.usage': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_resources_usage.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_resources_usage.resource,
  },
  'dev.session.archive': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_archive.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_archive.resource,
  },
  'dev.session.cancelHarness': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_cancelHarness.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_cancelHarness.resource,
  },
  'dev.session.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_create.resource,
  },
  'dev.session.events': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_events.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_events.resource,
  },
  'dev.session.get': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_get.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_get.resource,
  },
  'dev.session.launchDefault': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_launchDefault.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_launchDefault.resource,
  },
  'dev.session.launchHarness': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_launchHarness.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_launchHarness.resource,
  },
  'dev.session.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_list.resource,
  },
  'dev.session.resumeHarness': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_resumeHarness.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_resumeHarness.resource,
  },
  'dev.session.transferInput': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_transferInput.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_transferInput.resource,
  },
  'dev.session.unarchive': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_session_unarchive.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_session_unarchive.resource,
  },
  'dev.terminal.attach': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_attach.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_attach.resource,
  },
  'dev.terminal.checkpoint': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_checkpoint.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_checkpoint.resource,
  },
  'dev.terminal.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_create.resource,
  },
  'dev.terminal.detach': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_detach.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_detach.resource,
  },
  'dev.terminal.historyDelete': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_historyDelete.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_historyDelete.resource,
  },
  'dev.terminal.input': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_input.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_input.resource,
  },
  'dev.terminal.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_list.resource,
  },
  'dev.terminal.resize': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_resize.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_resize.resource,
  },
  'dev.terminal.search': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_search.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_search.resource,
  },
  'dev.terminal.shellProfiles': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_shellProfiles.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_shellProfiles.resource,
  },
  'dev.terminal.signal': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_signal.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_signal.resource,
  },
  'dev.terminal.terminate': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_terminal_terminate.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_terminal_terminate.resource,
  },
  'dev.worktree.archive': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_archive.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_archive.resource,
  },
  'dev.worktree.cleanupCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupCommit.resource,
  },
  'dev.worktree.cleanupJobs': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupJobs.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupJobs.resource,
  },
  'dev.worktree.cleanupPlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupPlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupPlan.resource,
  },
  'dev.worktree.cleanupResume': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupResume.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_cleanupResume.resource,
  },
  'dev.worktree.create': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_create.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_create.resource,
  },
  'dev.worktree.lease': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_lease.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_lease.resource,
  },
  'dev.worktree.list': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_list.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_list.resource,
  },
  'dev.worktree.mergeCommit': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_mergeCommit.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_mergeCommit.resource,
  },
  'dev.worktree.mergePlan': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_mergePlan.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_mergePlan.resource,
  },
  'dev.worktree.releaseLease': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_releaseLease.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_releaseLease.resource,
  },
  'dev.worktree.retryBootstrap': {
    capabilities:
      operationMetadata.devOperationMetadataFor_dev_worktree_retryBootstrap.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_retryBootstrap.resource,
  },
  'dev.worktree.unarchive': {
    capabilities: operationMetadata.devOperationMetadataFor_dev_worktree_unarchive.capabilities,
    resource: operationMetadata.devOperationMetadataFor_dev_worktree_unarchive.resource,
  },
} as const
