import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const read = (path: string) => readFileSync(resolve(root, path), 'utf8')

describe('Dev View dependency and bundle boundaries', () => {
  test('loads the Dev package only through the workspace navigation dynamic boundary', () => {
    const navigation = read('apps/web/src/components/workspace-navigation.tsx')
    expect(navigation).toContain("import('@adea-ai/dev-view')")
    expect(navigation).toContain("import('@adea-ai/ui/dev-view.css')")
    expect(navigation).not.toMatch(/^import .*@adea-ai\/dev-view/m)

    for (const entry of [
      'apps/web/src/start/workspace-mount.tsx',
      'apps/web/src/components/workspace-entry.tsx',
    ]) {
      expect(read(entry)).not.toContain('@adea-ai/dev-view')
    }
  })

  test('keeps privileged libraries and donor frameworks out of the shared package', () => {
    const manifest = read('packages/dev-view/package.json')
    for (const forbidden of [
      '@xterm/xterm',
      '@codemirror',
      'electron',
      'react',
      'zustand',
      '@pierre/',
    ]) {
      expect(manifest).not.toContain(`"${forbidden}`)
    }
    const source = [
      read('packages/dev-view/src/dev-workspace-entry.tsx'),
      read('packages/dev-view/src/layout/operations.ts'),
      read('packages/dev-view/src/layout/persistence.ts'),
    ].join('\n')
    expect(source).not.toContain('desktopInvoke(')
    expect(source).not.toContain('localStorage')
    const desktopSeam = read('apps/web/src/lib/desktop-dev-runtime.ts')
    expect(desktopSeam).toContain('channel_unauthenticated')
    expect(desktopSeam).not.toContain('desktopInvoke')
    expect(desktopSeam).not.toContain("from './desktop-bridge'")
  })

  test('pins generated decoders to the normative operation registry', () => {
    const generator = read('scripts/generate-dev-runtime-contract.mjs')
    expect(generator).toContain('docs/specs/dev-runtime-operations.json')
    expect(generator).toContain("'--check'")
    expect(read('packages/types/src/dev-runtime-registry.ts')).toContain(
      'Generated by scripts/generate-dev-runtime-contract.mjs'
    )
  })
})
