// Generated from openai/plugins at 1e285826e604f66f7208f7ac4dba0fe8341d1f57.
// Refresh automatically with: bun run plugins:sync
import type { WorkspacePluginDefinition } from './platform'

export const codexPluginMarketplaceRevision = '1e285826e604f66f7208f7ac4dba0fe8341d1f57'
export const codexPluginCatalog = Object.freeze([
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Productivity',
    description: 'Plan and build products',
    iconKey: 'codex:linear',
    id: 'linear',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Linear',
    ownership: 'public',
    publisher: 'Linear Orbit, Inc',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/linear',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector', 'Agent roles'],
    category: 'Productivity',
    description: 'Manage Jira and Confluence',
    iconKey: 'codex:atlassian-rovo',
    id: 'atlassian-rovo',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Atlassian Rovo',
    ownership: 'public',
    publisher: 'Atlassian',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/atlassian-rovo',
    surfaces: ['app', 'mcp', 'agent'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector'],
    category: 'Productivity',
    description: 'Manage Google Calendar events',
    iconKey: 'codex:google-calendar',
    id: 'google-calendar',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Google Calendar',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/google-calendar',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector'],
    category: 'Communication',
    description: 'Read and manage Gmail',
    iconKey: 'codex:gmail',
    id: 'gmail',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Gmail',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/gmail',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector'],
    category: 'Communication',
    description: 'Read and manage Slack',
    iconKey: 'codex:slack',
    id: 'slack',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Slack',
    ownership: 'public',
    publisher: 'Slack',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/slack',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector'],
    category: 'Communication',
    description: 'Summarize Teams and follow up',
    iconKey: 'codex:teams',
    id: 'teams',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Teams',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/teams',
    surfaces: ['app'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector'],
    category: 'Productivity',
    description: 'Summarize SharePoint content',
    iconKey: 'codex:sharepoint',
    id: 'sharepoint',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'SharePoint',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/sharepoint',
    surfaces: ['app'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector'],
    category: 'Communication',
    description: 'Triage Outlook inboxes',
    iconKey: 'codex:outlook-email',
    id: 'outlook-email',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Outlook Email',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/outlook-email',
    surfaces: ['app'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector'],
    category: 'Productivity',
    description: 'Manage Outlook schedules',
    iconKey: 'codex:outlook-calendar',
    id: 'outlook-calendar',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Outlook Calendar',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/outlook-calendar',
    surfaces: ['app'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Creativity',
    description: 'Create, review, edit designs',
    iconKey: 'codex:canva',
    id: 'canva',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Canva',
    ownership: 'public',
    publisher: 'Canva Pty Ltd.',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/canva',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: [
      'Interactive',
      'Read',
      'Write',
      'App connector',
      'MCP connector',
      'Skills',
      'Agent roles',
      'Commands',
      'Hooks',
    ],
    category: 'Creativity',
    description: 'Figma design-to-code workflows',
    iconKey: 'codex:figma',
    id: 'figma',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'LicenseRef-Figma-Developer-Terms',
    name: 'Figma',
    ownership: 'public',
    publisher: 'Figma',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/figma',
    surfaces: ['app', 'mcp', 'skill', 'agent', 'command', 'hook'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Finance',
    description: 'Accept payments. Grow revenue.',
    iconKey: 'codex:stripe',
    id: 'stripe',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Stripe',
    ownership: 'public',
    publisher: 'Stripe',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/stripe',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: [
      'Interactive',
      'Write',
      'App connector',
      'MCP connector',
      'Skills',
      'Agent roles',
      'Commands',
    ],
    category: 'Developer Tools',
    description: 'Build and deploy web apps and agents',
    iconKey: 'codex:vercel',
    id: 'vercel',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Apache-2.0',
    name: 'Vercel',
    ownership: 'public',
    publisher: 'Vercel Labs',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/vercel',
    surfaces: ['app', 'mcp', 'skill', 'agent', 'command'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Design, prototype, and ship browser games',
    iconKey: 'codex:game-studio',
    id: 'game-studio',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Game Studio',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/game-studio',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Hooks'],
    category: 'Developer Tools',
    description: 'Plan, develop, and debug code',
    iconKey: 'codex:superpowers',
    id: 'superpowers',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Superpowers',
    ownership: 'public',
    publisher: 'Jesse Vincent',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/superpowers',
    surfaces: ['skill', 'hook'],
  },
  {
    auth: 'api-key',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector'],
    category: 'Developer Tools',
    description: 'Triage PRs, issues, CI, and publish flows',
    iconKey: 'codex:github',
    id: 'github',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'GitHub',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/github',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Build, test, and deploy any application',
    iconKey: 'codex:circleci',
    id: 'circleci',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'CircleCI',
    ownership: 'public',
    publisher: 'CircleCI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/circleci',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Productivity',
    description: 'Drive, Docs, Sheets or Slides',
    iconKey: 'codex:google-drive',
    id: 'google-drive',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Google Drive',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/google-drive',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: [
      'Interactive',
      'Read',
      'Write',
      'App connector',
      'MCP connector',
      'Skills',
      'Agent roles',
    ],
    category: 'Productivity',
    description: 'Notion workflows for specs, research, meetings, and knowledge capture',
    iconKey: 'codex:notion',
    id: 'notion',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Notion',
    ownership: 'public',
    publisher: 'Notion',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/notion',
    surfaces: ['app', 'mcp', 'skill', 'agent'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'MCP connector', 'Skills', 'Commands'],
    category: 'Developer Tools',
    description: 'Cloudflare platform guidance with official MCP',
    iconKey: 'codex:cloudflare',
    id: 'cloudflare',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Cloudflare',
    ownership: 'public',
    publisher: 'Cloudflare',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/cloudflare',
    surfaces: ['mcp', 'skill', 'command'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'MCP connector', 'Skills'],
    category: 'Developer Tools',
    description: 'Inspect recent Sentry issues and events',
    iconKey: 'codex:sentry',
    id: 'sentry',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Sentry',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/sentry',
    surfaces: ['mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'MCP connector', 'Skills', 'Agent roles'],
    category: 'Developer Tools',
    description: 'Build, refine, and debug iOS apps with App Intents, SwiftUI, and Xcode workflows',
    iconKey: 'codex:build-ios-apps',
    id: 'build-ios-apps',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Build iOS Apps',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-ios-apps',
    surfaces: ['mcp', 'skill', 'agent'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Agent roles', 'Commands'],
    category: 'Developer Tools',
    description:
      'Build, debug, instrument, and implement macOS apps with SwiftUI and AppKit guidance',
    iconKey: 'codex:build-macos-apps',
    id: 'build-macos-apps',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Build macOS Apps',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-macos-apps',
    surfaces: ['skill', 'agent', 'command'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Agent roles'],
    category: 'Developer Tools',
    description:
      'Build frontend-focused web apps with generated assets, browser testing, payments, and databases',
    iconKey: 'codex:build-web-apps',
    id: 'build-web-apps',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Build Web Apps',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-web-apps',
    surfaces: ['skill', 'agent'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Agent roles'],
    category: 'Developer Tools',
    description: 'Design, build, test, and export web data visualizations',
    iconKey: 'codex:build-web-data-visualization',
    id: 'build-web-data-visualization',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Build Web Data Visualization',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-web-data-visualization',
    surfaces: ['skill', 'agent'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Skills', 'Agent roles'],
    category: 'Developer Tools',
    description:
      'Reproduce issues, inspect UI, and capture performance evidence from Android emulators',
    iconKey: 'codex:test-android-apps',
    id: 'test-android-apps',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Test Android Apps',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/test-android-apps',
    surfaces: ['skill', 'agent'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Education & Research',
    description:
      'General life-sciences research with routing, evidence synthesis, and optional parallel subagent analysis',
    iconKey: 'codex:life-science-research',
    id: 'life-science-research',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'Proprietary',
    name: 'Life Science Research',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/life-science-research',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Education & Research',
    description: 'Find papers and add citations from Zotero',
    iconKey: 'codex:zotero',
    id: 'zotero',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Zotero',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/zotero',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Agent roles', 'Commands'],
    category: 'Developer Tools',
    description: 'Build, deploy, upgrade, and debug Expo and React Native apps',
    iconKey: 'codex:expo',
    id: 'expo',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Expo',
    ownership: 'public',
    publisher: 'Expo',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/expo',
    surfaces: ['skill', 'agent', 'command'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Run AI-powered code review for your current changes',
    iconKey: 'codex:coderabbit',
    id: 'coderabbit',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'CodeRabbit',
    ownership: 'public',
    publisher: 'CodeRabbit',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/coderabbit',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Read', 'Write', 'Skills'],
    category: 'Creativity',
    description: 'Make videos agentically',
    iconKey: 'codex:remotion',
    id: 'remotion',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Remotion',
    ownership: 'public',
    publisher: 'Remotion',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/remotion',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Start from chat, then evaluate or benchmark locally',
    iconKey: 'codex:plugin-eval',
    id: 'plugin-eval',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Plugin Eval',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/plugin-eval',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Productivity',
    description: 'Add your meeting context',
    iconKey: 'codex:granola',
    id: 'granola',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Granola',
    ownership: 'public',
    publisher: 'Granola',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/granola',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Productivity',
    description: 'Manage projects, tasks & CRM',
    iconKey: 'codex:monday-com',
    id: 'monday-com',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'monday.com',
    ownership: 'public',
    publisher: 'monday.com',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/monday-com',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Skills'],
    category: 'Developer Tools',
    description: 'Develop with Temporal',
    iconKey: 'codex:temporal',
    id: 'temporal',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Temporal',
    ownership: 'public',
    publisher: 'Temporal',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/temporal',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Read', 'Write', 'Skills'],
    category: 'Creativity',
    description: 'Write HTML, render video',
    iconKey: 'codex:hyperframes',
    id: 'hyperframes',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'Apache-2.0',
    name: 'HyperFrames by HeyGen',
    ownership: 'public',
    publisher: 'HeyGen',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/hyperframes',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Read', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Developer Tools',
    description: 'Manage and query databases',
    iconKey: 'codex:supabase',
    id: 'supabase',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Supabase',
    ownership: 'public',
    publisher: 'Supabase',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/supabase',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Security',
    description: 'Scan your codebase for risks',
    iconKey: 'codex:codex-security',
    id: 'codex-security',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Proprietary',
    name: 'Codex Security',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/codex-security',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Read', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Twilio Skills for building, debugging, and shipping on Twilio',
    iconKey: 'codex:twilio-developer-kit',
    id: 'twilio-developer-kit',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Twilio Developer Kit',
    ownership: 'public',
    publisher: 'Twilio',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/twilio-developer-kit',
    surfaces: ['skill'],
  },
  {
    auth: 'api-key',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Developer Tools',
    description: 'Develop AI apps, agents, and ChatGPT Apps with OpenAI best practices',
    iconKey: 'codex:openai-developers',
    id: 'openai-developers',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Proprietary',
    name: 'OpenAI Developers',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/openai-developers',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Developer Tools',
    description: 'Search and act on your data',
    iconKey: 'codex:datadog',
    id: 'datadog',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Datadog (Preview)',
    ownership: 'public',
    publisher: 'Datadog',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/datadog',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: [
      'Interactive',
      'Read',
      'Write',
      'App connector',
      'MCP connector',
      'Skills',
      'Agent roles',
      'Commands',
    ],
    category: 'Communication',
    description: 'Smart meeting insights from Zoom',
    iconKey: 'codex:zoom',
    id: 'zoom',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'Zoom',
    ownership: 'public',
    publisher: 'Zoom',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/zoom',
    surfaces: ['app', 'mcp', 'skill', 'agent', 'command'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Data & Analytics',
    description: 'Analyze Mixpanel data with Python',
    iconKey: 'codex:mixpanel-headless',
    id: 'mixpanel-headless',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Mixpanel Headless',
    ownership: 'public',
    publisher: 'Mixpanel',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/mixpanel-headless',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Productivity',
    description: 'Add structured data to ChatGPT',
    iconKey: 'codex:airtable',
    id: 'airtable',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Airtable',
    ownership: 'public',
    publisher: 'Airtable',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/airtable',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Guided help for NVIDIA AI, GPU, robotics, simulation, and 3D workflows.',
    iconKey: 'codex:nvidia',
    id: 'nvidia',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'Apache-2.0 AND CC-BY-4.0',
    name: 'NVIDIA',
    ownership: 'public',
    publisher: 'NVIDIA',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/nvidia',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Data & Analytics',
    description: 'Analyze your product data',
    iconKey: 'codex:posthog',
    id: 'posthog',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'PostHog',
    ownership: 'public',
    publisher: 'PostHog Inc.',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/posthog',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Education & Research',
    description: 'Guided NGS routing and local execution for sequencing analysis',
    iconKey: 'codex:ngs-analysis',
    id: 'ngs-analysis',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Life Sciences NGS Analysis',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/ngs-analysis',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Business & Operations',
    description: 'Build and manage your store',
    iconKey: 'codex:shopify',
    id: 'shopify',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Shopify',
    ownership: 'public',
    publisher: 'Shopify',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/shopify',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Find, install, and author MagicPath UI components from Codex',
    iconKey: 'codex:magicpath',
    id: 'magicpath',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'UNLICENSED',
    name: 'MagicPath',
    ownership: 'public',
    publisher: 'MagicPathAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/magicpath',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills'],
    category: 'Developer Tools',
    description: 'Set up OpenAI Ads Pixel and CAPI tracking',
    iconKey: 'codex:openai-ads-conversions',
    id: 'openai-ads-conversions',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'Proprietary',
    name: 'OpenAI Ads Conversions',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/openai-ads-conversions',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'Skills'],
    category: 'Scientific Research',
    description: 'Predict structures, screen molecules and proteins, and design binders',
    iconKey: 'codex:boltz-api-cli',
    id: 'boltz-api-cli',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'MIT',
    name: 'Boltz',
    ownership: 'public',
    publisher: 'Boltz',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/boltz-api-cli',
    surfaces: ['skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Productivity',
    description: 'Access, save and share files',
    iconKey: 'codex:dropbox',
    id: 'dropbox',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Dropbox',
    ownership: 'public',
    publisher: 'Dropbox',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/dropbox',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'Skills', 'Agent roles'],
    category: 'Creativity',
    description: 'Explore and prototype ideas',
    iconKey: 'codex:product-design',
    id: 'product-design',
    installationPolicy: 'available',
    kind: 'skill',
    license: 'Proprietary',
    name: 'Product Design',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/product-design',
    surfaces: ['skill', 'agent'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Data & Analytics',
    description: 'Answer product and business questions with data',
    iconKey: 'codex:data-analytics',
    id: 'data-analytics',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Proprietary',
    name: 'Data Analytics',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/data-analytics',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Write', 'App connector', 'MCP connector', 'Skills'],
    category: 'Creativity',
    description: 'Create marketing visuals from a brief or product image.',
    iconKey: 'codex:creative-production',
    id: 'creative-production',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Proprietary',
    name: 'Creative Production',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/creative-production',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-use',
    capabilities: ['Interactive', 'Read', 'Write', 'App connector', 'Skills'],
    category: 'Finance',
    description: 'Public equity PM research, long/short, earnings, ETF/index diligence, and memos',
    iconKey: 'codex:public-equity-investing',
    id: 'public-equity-investing',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'Proprietary',
    name: 'Public Equity Investing',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/public-equity-investing',
    surfaces: ['app', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'Skills'],
    category: 'Creativity',
    description: 'Design, combine, and edit',
    iconKey: 'codex:adobe',
    id: 'adobe',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Adobe',
    ownership: 'public',
    publisher: 'Adobe Inc',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/adobe',
    surfaces: ['app', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector'],
    category: 'Developer Tools',
    description: 'Build apps and websites',
    iconKey: 'codex:lovable',
    id: 'lovable',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Lovable',
    ownership: 'public',
    publisher: 'Lovable Labs',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/lovable',
    surfaces: ['app'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Productivity',
    description: 'Turn Codex into your ClickUp command center.',
    iconKey: 'codex:clickup',
    id: 'clickup',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'MIT',
    name: 'ClickUp',
    ownership: 'public',
    publisher: 'ClickUp',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/clickup',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector'],
    category: 'Education & Research',
    description: 'Explore scientific research',
    iconKey: 'codex:consensus',
    id: 'consensus',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Consensus',
    ownership: 'public',
    publisher: 'Consensus',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/consensus',
    surfaces: ['app', 'mcp'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['Interactive', 'Write', 'App connector', 'Skills'],
    category: 'Creativity',
    description: 'Install and connect ChatCut',
    iconKey: 'codex:chatcut',
    id: 'chatcut',
    installationPolicy: 'available',
    kind: 'connector',
    license: 'GPL-3.0-only',
    name: 'ChatCut',
    ownership: 'public',
    publisher: 'ChatCut',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/chatcut',
    surfaces: ['app', 'skill'],
  },
  {
    auth: 'oauth',
    authenticationPolicy: 'on-install',
    capabilities: ['App connector', 'MCP connector', 'Skills'],
    category: 'Creativity',
    description: 'Every image and video model',
    iconKey: 'codex:higgsfield',
    id: 'higgsfield',
    installationPolicy: 'available',
    kind: 'connector',
    name: 'Higgsfield',
    ownership: 'public',
    publisher: 'Higgsfield AI, Inc.',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl:
      'https://github.com/openai/plugins/tree/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/higgsfield',
    surfaces: ['app', 'mcp', 'skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Skills'],
    category: 'Developer Tools',
    description: 'crowdstrike-falcon-foundry from the Codex official marketplace.',
    iconKey: 'codex:crowdstrike-falcon-foundry',
    id: 'crowdstrike-falcon-foundry',
    installationPolicy: 'available',
    kind: 'skill',
    name: 'crowdstrike-falcon-foundry',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl: 'https://github.com/CrowdStrike/foundry-skills.git',
    surfaces: ['skill'],
  },
  {
    auth: 'workspace',
    authenticationPolicy: 'on-install',
    capabilities: ['Skills'],
    category: 'Developer Tools',
    description: 'crowdstrike-falcon-fusion from the Codex official marketplace.',
    iconKey: 'codex:crowdstrike-falcon-fusion',
    id: 'crowdstrike-falcon-fusion',
    installationPolicy: 'available',
    kind: 'skill',
    name: 'crowdstrike-falcon-fusion',
    ownership: 'public',
    publisher: 'OpenAI',
    source: 'codex-official',
    sourceRevision: '1e285826e604f66f7208f7ac4dba0fe8341d1f57',
    sourceUrl: 'https://github.com/CrowdStrike/fusion-skills.git',
    surfaces: ['skill'],
  },
]) satisfies readonly WorkspacePluginDefinition[]
export const codexPluginLogoUrls: Readonly<Record<string, string>> = Object.freeze({
  linear:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/linear/assets/logo.png',
  'atlassian-rovo':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/atlassian-rovo/assets/logo.png',
  'google-calendar':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/google-calendar/assets/logo.png',
  gmail:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/gmail/assets/gmail.png',
  slack:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/slack/assets/logo.png',
  teams:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/teams/assets/logo.png',
  sharepoint:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/sharepoint/assets/logo.png',
  'outlook-email':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/outlook-email/assets/logo.png',
  'outlook-calendar':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/outlook-calendar/assets/logo.png',
  canva:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/canva/assets/logo.png',
  figma:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/figma/assets/logo-padded.png',
  stripe:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/stripe/assets/logo.png',
  vercel:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/vercel/assets/logo.png',
  'game-studio':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/game-studio/assets/app-icon.png',
  superpowers:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/superpowers/.codex-plugin/assets/logo.png',
  github:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/github/assets/github.png',
  circleci:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/circleci/assets/logo.png',
  'google-drive':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/google-drive/assets/logo.png',
  notion:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/notion/assets/notion.png',
  cloudflare:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/cloudflare/assets/cloudflare.png',
  sentry:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/sentry/assets/sentry.png',
  'build-ios-apps':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-ios-apps/assets/app-icon.png',
  'build-macos-apps':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-macos-apps/assets/app-icon.png',
  'build-web-apps':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-web-apps/assets/app-icon.png',
  'build-web-data-visualization':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/build-web-data-visualization/assets/app-icon.svg',
  'test-android-apps':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/test-android-apps/assets/app-icon.png',
  'life-science-research':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/life-science-research/assets/app-icon.png',
  zotero:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/zotero/assets/icon.png',
  expo: 'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/expo/assets/expo.png',
  coderabbit:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/coderabbit/assets/logo.png',
  remotion:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/remotion/.codex-plugin/assets/logo.png',
  'plugin-eval':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/plugin-eval/assets/plugin-eval.svg',
  granola:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/granola/assets/logo.png',
  'monday-com':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/monday-com/assets/logo.png',
  temporal:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/temporal/.codex-plugin/assets/logo.svg',
  hyperframes:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/hyperframes/assets/logo.png',
  supabase:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/supabase/assets/logo.png',
  'codex-security':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/codex-security/assets/logo.png',
  'twilio-developer-kit':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/twilio-developer-kit/assets/logo.svg',
  'openai-developers':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/openai-developers/assets/logo.png',
  datadog:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/datadog/assets/logo.png',
  zoom: 'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/zoom/assets/logo.jpg',
  'mixpanel-headless':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/mixpanel-headless/assets/logo.png',
  airtable:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/airtable/assets/logo.png',
  nvidia:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/nvidia/assets/nvidia.png',
  posthog:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/posthog/assets/logo.png',
  'ngs-analysis':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/ngs-analysis/assets/app-icon.png',
  shopify:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/shopify/assets/logo.png',
  magicpath:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/magicpath/assets/magicpath.png',
  'openai-ads-conversions':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/openai-ads-conversions/assets/icon.svg',
  'boltz-api-cli':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/boltz-api-cli/assets/app-icon.png',
  dropbox:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/dropbox/assets/logo.png',
  'product-design':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/product-design/assets/logo.png',
  'data-analytics':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/data-analytics/assets/datascience.png',
  'creative-production':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/creative-production/assets/logo.png',
  'public-equity-investing':
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/public-equity-investing/assets/logo.png',
  clickup:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/clickup/assets/logo.png',
  chatcut:
    'https://raw.githubusercontent.com/openai/plugins/1e285826e604f66f7208f7ac4dba0fe8341d1f57/plugins/chatcut/.codex-plugin/assets/logo.png',
})
