name: Code Foundry

on:
  push:
    branches: [main]

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    uses: 0xPlayerOne/code-foundry/.github/workflows/release.yml@v1.0.6
    with:
      runner: ubuntu-latest
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: v1.0.6
    secrets:
      CODE_FOUNDRY_TOKEN: ${{ secrets.CODE_FOUNDRY_TOKEN }}
      STAGING_DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
